// Code generated by MockGen. DO NOT EDIT.
// Source: spotify/microservices/playlist/service (interfaces: IRepository)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/repository/repository_mock.go -package=repository_mock spotify/microservices/playlist/service IRepository
//

// Package repository_mock is a generated GoMock package.
package repository_mock

import (
	context "context"
	reflect "reflect"
	model "spotify/internal/model"
	postgres "spotify/microservices/playlist/repository/postgres"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockIRepository is a mock of IRepository interface.
type MockIRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIRepositoryMockRecorder
	isgomock struct{}
}

// MockIRepositoryMockRecorder is the mock recorder for MockIRepository.
type MockIRepositoryMockRecorder struct {
	mock *MockIRepository
}

// NewMockIRepository creates a new mock instance.
func NewMockIRepository(ctrl *gomock.Controller) *MockIRepository {
	mock := &MockIRepository{ctrl: ctrl}
	mock.recorder = &MockIRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRepository) EXPECT() *MockIRepositoryMockRecorder {
	return m.recorder
}

// AddTrackToPlaylist mocks base method.
func (m *MockIRepository) AddTrackToPlaylist(ctx context.Context, playlistID uuid.UUID, trackID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTrackToPlaylist", ctx, playlistID, trackID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTrackToPlaylist indicates an expected call of AddTrackToPlaylist.
func (mr *MockIRepositoryMockRecorder) AddTrackToPlaylist(ctx, playlistID, trackID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTrackToPlaylist", reflect.TypeOf((*MockIRepository)(nil).AddTrackToPlaylist), ctx, playlistID, trackID)
}

// CreatePlaylist mocks base method.
func (m *MockIRepository) CreatePlaylist(ctx context.Context, playlist model.Playlist, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePlaylist", ctx, playlist, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePlaylist indicates an expected call of CreatePlaylist.
func (mr *MockIRepositoryMockRecorder) CreatePlaylist(ctx, playlist, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePlaylist", reflect.TypeOf((*MockIRepository)(nil).CreatePlaylist), ctx, playlist, userID)
}

// DeletePlaylist mocks base method.
func (m *MockIRepository) DeletePlaylist(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePlaylist", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePlaylist indicates an expected call of DeletePlaylist.
func (mr *MockIRepositoryMockRecorder) DeletePlaylist(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePlaylist", reflect.TypeOf((*MockIRepository)(nil).DeletePlaylist), ctx, id)
}

// GetAllByUser mocks base method.
func (m *MockIRepository) GetAllByUser(ctx context.Context, userID uuid.UUID, limit, offset uint64) ([]model.Playlist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllByUser", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]model.Playlist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllByUser indicates an expected call of GetAllByUser.
func (mr *MockIRepositoryMockRecorder) GetAllByUser(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllByUser", reflect.TypeOf((*MockIRepository)(nil).GetAllByUser), ctx, userID, limit, offset)
}

// GetByID mocks base method.
func (m *MockIRepository) GetByID(ctx context.Context, id uuid.UUID) (*model.Playlist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.Playlist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockIRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockIRepository)(nil).GetByID), ctx, id)
}

// GetFavoritePlaylist mocks base method.
func (m *MockIRepository) GetFavoritePlaylist(ctx context.Context, userID uuid.UUID) (*model.Playlist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFavoritePlaylist", ctx, userID)
	ret0, _ := ret[0].(*model.Playlist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFavoritePlaylist indicates an expected call of GetFavoritePlaylist.
func (mr *MockIRepositoryMockRecorder) GetFavoritePlaylist(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFavoritePlaylist", reflect.TypeOf((*MockIRepository)(nil).GetFavoritePlaylist), ctx, userID)
}

// GetTracksByPlaylist mocks base method.
func (m *MockIRepository) GetTracksByPlaylist(ctx context.Context, playlistID uuid.UUID) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTracksByPlaylist", ctx, playlistID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTracksByPlaylist indicates an expected call of GetTracksByPlaylist.
func (mr *MockIRepositoryMockRecorder) GetTracksByPlaylist(ctx, playlistID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTracksByPlaylist", reflect.TypeOf((*MockIRepository)(nil).GetTracksByPlaylist), ctx, playlistID)
}

// RemoveTrackFromPlaylist mocks base method.
func (m *MockIRepository) RemoveTrackFromPlaylist(ctx context.Context, playlistID uuid.UUID, trackID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveTrackFromPlaylist", ctx, playlistID, trackID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveTrackFromPlaylist indicates an expected call of RemoveTrackFromPlaylist.
func (mr *MockIRepositoryMockRecorder) RemoveTrackFromPlaylist(ctx, playlistID, trackID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveTrackFromPlaylist", reflect.TypeOf((*MockIRepository)(nil).RemoveTrackFromPlaylist), ctx, playlistID, trackID)
}

// UpdatePlaylist mocks base method.
func (m *MockIRepository) UpdatePlaylist(ctx context.Context, id uuid.UUID, upd postgres.PlaylistUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePlaylist", ctx, id, upd)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePlaylist indicates an expected call of UpdatePlaylist.
func (mr *MockIRepositoryMockRecorder) UpdatePlaylist(ctx, id, upd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePlaylist", reflect.TypeOf((*MockIRepository)(nil).UpdatePlaylist), ctx, id, upd)
}

// UpdatePlaylistAvatar mocks base method.
func (m *MockIRepository) UpdatePlaylistAvatar(ctx context.Context, id uuid.UUID, avatar string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePlaylistAvatar", ctx, id, avatar)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePlaylistAvatar indicates an expected call of UpdatePlaylistAvatar.
func (mr *MockIRepositoryMockRecorder) UpdatePlaylistAvatar(ctx, id, avatar any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePlaylistAvatar", reflect.TypeOf((*MockIRepository)(nil).UpdatePlaylistAvatar), ctx, id, avatar)
}
