// Code generated by MockGen. DO NOT EDIT.
// Source: spotify/internal/track/service (interfaces: IRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/track/repository_mock.go -package=track spotify/internal/track/service IRepository
//

// Package track is a generated GoMock package.
package track

import (
	context "context"
	reflect "reflect"
	model "spotify/internal/model"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockIRepository is a mock of IRepository interface.
type MockIRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIRepositoryMockRecorder
	isgomock struct{}
}

// MockIRepositoryMockRecorder is the mock recorder for MockIRepository.
type MockIRepositoryMockRecorder struct {
	mock *MockIRepository
}

// NewMockIRepository creates a new mock instance.
func NewMockIRepository(ctrl *gomock.Controller) *MockIRepository {
	mock := &MockIRepository{ctrl: ctrl}
	mock.recorder = &MockIRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRepository) EXPECT() *MockIRepositoryMockRecorder {
	return m.recorder
}

// GetAlbumIDsForTracks mocks base method.
func (m *MockIRepository) GetAlbumIDsForTracks(ctx context.Context, trackIDs []uuid.UUID) (map[uuid.UUID]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAlbumIDsForTracks", ctx, trackIDs)
	ret0, _ := ret[0].(map[uuid.UUID]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAlbumIDsForTracks indicates an expected call of GetAlbumIDsForTracks.
func (mr *MockIRepositoryMockRecorder) GetAlbumIDsForTracks(ctx, trackIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAlbumIDsForTracks", reflect.TypeOf((*MockIRepository)(nil).GetAlbumIDsForTracks), ctx, trackIDs)
}

// GetAll mocks base method.
func (m *MockIRepository) GetAll(ctx context.Context, limit, offset uint64) ([]model.Track, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, limit, offset)
	ret0, _ := ret[0].([]model.Track)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockIRepositoryMockRecorder) GetAll(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockIRepository)(nil).GetAll), ctx, limit, offset)
}

// GetArtistIDsForTracks mocks base method.
func (m *MockIRepository) GetArtistIDsForTracks(ctx context.Context, trackIDs []uuid.UUID) (map[uuid.UUID][]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArtistIDsForTracks", ctx, trackIDs)
	ret0, _ := ret[0].(map[uuid.UUID][]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArtistIDsForTracks indicates an expected call of GetArtistIDsForTracks.
func (mr *MockIRepositoryMockRecorder) GetArtistIDsForTracks(ctx, trackIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArtistIDsForTracks", reflect.TypeOf((*MockIRepository)(nil).GetArtistIDsForTracks), ctx, trackIDs)
}

// GetByAlbumID mocks base method.
func (m *MockIRepository) GetByAlbumID(ctx context.Context, albumID uuid.UUID, limit, offset uint64) ([]model.Track, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAlbumID", ctx, albumID, limit, offset)
	ret0, _ := ret[0].([]model.Track)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByAlbumID indicates an expected call of GetByAlbumID.
func (mr *MockIRepositoryMockRecorder) GetByAlbumID(ctx, albumID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAlbumID", reflect.TypeOf((*MockIRepository)(nil).GetByAlbumID), ctx, albumID, limit, offset)
}

// GetByArtistID mocks base method.
func (m *MockIRepository) GetByArtistID(ctx context.Context, artistID uuid.UUID, limit, offset uint64) ([]model.Track, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByArtistID", ctx, artistID, limit, offset)
	ret0, _ := ret[0].([]model.Track)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByArtistID indicates an expected call of GetByArtistID.
func (mr *MockIRepositoryMockRecorder) GetByArtistID(ctx, artistID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByArtistID", reflect.TypeOf((*MockIRepository)(nil).GetByArtistID), ctx, artistID, limit, offset)
}

// GetByGenreID mocks base method.
func (m *MockIRepository) GetByGenreID(ctx context.Context, genreID uuid.UUID, limit, offset uint64) ([]model.Track, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByGenreID", ctx, genreID, limit, offset)
	ret0, _ := ret[0].([]model.Track)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByGenreID indicates an expected call of GetByGenreID.
func (mr *MockIRepositoryMockRecorder) GetByGenreID(ctx, genreID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByGenreID", reflect.TypeOf((*MockIRepository)(nil).GetByGenreID), ctx, genreID, limit, offset)
}

// GetByID mocks base method.
func (m *MockIRepository) GetByID(ctx context.Context, id uuid.UUID) (*model.Track, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.Track)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockIRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockIRepository)(nil).GetByID), ctx, id)
}

// GetGenresForTracks mocks base method.
func (m *MockIRepository) GetGenresForTracks(ctx context.Context, trackIDs []uuid.UUID) (map[uuid.UUID][]model.Genre, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGenresForTracks", ctx, trackIDs)
	ret0, _ := ret[0].(map[uuid.UUID][]model.Genre)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGenresForTracks indicates an expected call of GetGenresForTracks.
func (mr *MockIRepositoryMockRecorder) GetGenresForTracks(ctx, trackIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGenresForTracks", reflect.TypeOf((*MockIRepository)(nil).GetGenresForTracks), ctx, trackIDs)
}
