// Code generated by MockGen. DO NOT EDIT.
// Source: spotify/microservices/catalog/service (interfaces: IRepository)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/repository/repository_mock.go -package=repository_mock spotify/microservices/catalog/service IRepository
//

// Package repository_mock is a generated GoMock package.
package repository_mock

import (
	context "context"
	reflect "reflect"
	model "spotify/internal/model"
	dto "spotify/microservices/catalog/dto"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockIRepository is a mock of IRepository interface.
type MockIRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIRepositoryMockRecorder
	isgomock struct{}
}

// MockIRepositoryMockRecorder is the mock recorder for MockIRepository.
type MockIRepositoryMockRecorder struct {
	mock *MockIRepository
}

// NewMockIRepository creates a new mock instance.
func NewMockIRepository(ctrl *gomock.Controller) *MockIRepository {
	mock := &MockIRepository{ctrl: ctrl}
	mock.recorder = &MockIRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRepository) EXPECT() *MockIRepositoryMockRecorder {
	return m.recorder
}

// GetAlbumByID mocks base method.
func (m *MockIRepository) GetAlbumByID(ctx context.Context, id uuid.UUID) (*model.Album, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAlbumByID", ctx, id)
	ret0, _ := ret[0].(*model.Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAlbumByID indicates an expected call of GetAlbumByID.
func (mr *MockIRepositoryMockRecorder) GetAlbumByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAlbumByID", reflect.TypeOf((*MockIRepository)(nil).GetAlbumByID), ctx, id)
}

// GetAlbumIDsForTracks mocks base method.
func (m *MockIRepository) GetAlbumIDsForTracks(ctx context.Context, trackIDs []uuid.UUID) (map[uuid.UUID]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAlbumIDsForTracks", ctx, trackIDs)
	ret0, _ := ret[0].(map[uuid.UUID]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAlbumIDsForTracks indicates an expected call of GetAlbumIDsForTracks.
func (mr *MockIRepositoryMockRecorder) GetAlbumIDsForTracks(ctx, trackIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAlbumIDsForTracks", reflect.TypeOf((*MockIRepository)(nil).GetAlbumIDsForTracks), ctx, trackIDs)
}

// GetAlbumsByArtistID mocks base method.
func (m *MockIRepository) GetAlbumsByArtistID(ctx context.Context, artistID uuid.UUID, limit, offset uint64) ([]model.Album, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAlbumsByArtistID", ctx, artistID, limit, offset)
	ret0, _ := ret[0].([]model.Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAlbumsByArtistID indicates an expected call of GetAlbumsByArtistID.
func (mr *MockIRepositoryMockRecorder) GetAlbumsByArtistID(ctx, artistID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAlbumsByArtistID", reflect.TypeOf((*MockIRepository)(nil).GetAlbumsByArtistID), ctx, artistID, limit, offset)
}

// GetAlbumsByIDs mocks base method.
func (m *MockIRepository) GetAlbumsByIDs(ctx context.Context, ids []uuid.UUID) ([]model.Album, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAlbumsByIDs", ctx, ids)
	ret0, _ := ret[0].([]model.Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAlbumsByIDs indicates an expected call of GetAlbumsByIDs.
func (mr *MockIRepositoryMockRecorder) GetAlbumsByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAlbumsByIDs", reflect.TypeOf((*MockIRepository)(nil).GetAlbumsByIDs), ctx, ids)
}

// GetAllAlbums mocks base method.
func (m *MockIRepository) GetAllAlbums(ctx context.Context, limit, offset uint64) ([]model.Album, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllAlbums", ctx, limit, offset)
	ret0, _ := ret[0].([]model.Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllAlbums indicates an expected call of GetAllAlbums.
func (mr *MockIRepositoryMockRecorder) GetAllAlbums(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllAlbums", reflect.TypeOf((*MockIRepository)(nil).GetAllAlbums), ctx, limit, offset)
}

// GetAllArtists mocks base method.
func (m *MockIRepository) GetAllArtists(ctx context.Context, limit, offset uint64) ([]model.Artist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllArtists", ctx, limit, offset)
	ret0, _ := ret[0].([]model.Artist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllArtists indicates an expected call of GetAllArtists.
func (mr *MockIRepositoryMockRecorder) GetAllArtists(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllArtists", reflect.TypeOf((*MockIRepository)(nil).GetAllArtists), ctx, limit, offset)
}

// GetAllTracks mocks base method.
func (m *MockIRepository) GetAllTracks(ctx context.Context, limit, offset uint64) ([]model.Track, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllTracks", ctx, limit, offset)
	ret0, _ := ret[0].([]model.Track)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllTracks indicates an expected call of GetAllTracks.
func (mr *MockIRepositoryMockRecorder) GetAllTracks(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTracks", reflect.TypeOf((*MockIRepository)(nil).GetAllTracks), ctx, limit, offset)
}

// GetArtistByID mocks base method.
func (m *MockIRepository) GetArtistByID(ctx context.Context, id uuid.UUID) (*model.Artist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArtistByID", ctx, id)
	ret0, _ := ret[0].(*model.Artist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArtistByID indicates an expected call of GetArtistByID.
func (mr *MockIRepositoryMockRecorder) GetArtistByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArtistByID", reflect.TypeOf((*MockIRepository)(nil).GetArtistByID), ctx, id)
}

// GetArtistIDsForTracks mocks base method.
func (m *MockIRepository) GetArtistIDsForTracks(ctx context.Context, trackIDs []uuid.UUID) (map[uuid.UUID][]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArtistIDsForTracks", ctx, trackIDs)
	ret0, _ := ret[0].(map[uuid.UUID][]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArtistIDsForTracks indicates an expected call of GetArtistIDsForTracks.
func (mr *MockIRepositoryMockRecorder) GetArtistIDsForTracks(ctx, trackIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArtistIDsForTracks", reflect.TypeOf((*MockIRepository)(nil).GetArtistIDsForTracks), ctx, trackIDs)
}

// GetArtistsByIDs mocks base method.
func (m *MockIRepository) GetArtistsByIDs(ctx context.Context, ids []uuid.UUID) ([]model.Artist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArtistsByIDs", ctx, ids)
	ret0, _ := ret[0].([]model.Artist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArtistsByIDs indicates an expected call of GetArtistsByIDs.
func (mr *MockIRepositoryMockRecorder) GetArtistsByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArtistsByIDs", reflect.TypeOf((*MockIRepository)(nil).GetArtistsByIDs), ctx, ids)
}

// GetGenresForTracks mocks base method.
func (m *MockIRepository) GetGenresForTracks(ctx context.Context, trackIDs []uuid.UUID) (map[uuid.UUID][]model.Genre, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGenresForTracks", ctx, trackIDs)
	ret0, _ := ret[0].(map[uuid.UUID][]model.Genre)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGenresForTracks indicates an expected call of GetGenresForTracks.
func (mr *MockIRepositoryMockRecorder) GetGenresForTracks(ctx, trackIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGenresForTracks", reflect.TypeOf((*MockIRepository)(nil).GetGenresForTracks), ctx, trackIDs)
}

// GetTotalPlaysByArtistID mocks base method.
func (m *MockIRepository) GetTotalPlaysByArtistID(ctx context.Context, artistID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalPlaysByArtistID", ctx, artistID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalPlaysByArtistID indicates an expected call of GetTotalPlaysByArtistID.
func (mr *MockIRepositoryMockRecorder) GetTotalPlaysByArtistID(ctx, artistID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalPlaysByArtistID", reflect.TypeOf((*MockIRepository)(nil).GetTotalPlaysByArtistID), ctx, artistID)
}

// GetTotalPlaysByArtistIDs mocks base method.
func (m *MockIRepository) GetTotalPlaysByArtistIDs(ctx context.Context, artistIDs []uuid.UUID) (map[uuid.UUID]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalPlaysByArtistIDs", ctx, artistIDs)
	ret0, _ := ret[0].(map[uuid.UUID]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalPlaysByArtistIDs indicates an expected call of GetTotalPlaysByArtistIDs.
func (mr *MockIRepositoryMockRecorder) GetTotalPlaysByArtistIDs(ctx, artistIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalPlaysByArtistIDs", reflect.TypeOf((*MockIRepository)(nil).GetTotalPlaysByArtistIDs), ctx, artistIDs)
}

// GetTrackByID mocks base method.
func (m *MockIRepository) GetTrackByID(ctx context.Context, id uuid.UUID) (*model.Track, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrackByID", ctx, id)
	ret0, _ := ret[0].(*model.Track)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTrackByID indicates an expected call of GetTrackByID.
func (mr *MockIRepositoryMockRecorder) GetTrackByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrackByID", reflect.TypeOf((*MockIRepository)(nil).GetTrackByID), ctx, id)
}

// GetTracksByAlbumID mocks base method.
func (m *MockIRepository) GetTracksByAlbumID(ctx context.Context, albumID uuid.UUID, limit, offset uint64) ([]model.Track, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTracksByAlbumID", ctx, albumID, limit, offset)
	ret0, _ := ret[0].([]model.Track)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTracksByAlbumID indicates an expected call of GetTracksByAlbumID.
func (mr *MockIRepositoryMockRecorder) GetTracksByAlbumID(ctx, albumID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTracksByAlbumID", reflect.TypeOf((*MockIRepository)(nil).GetTracksByAlbumID), ctx, albumID, limit, offset)
}

// GetTracksByArtistID mocks base method.
func (m *MockIRepository) GetTracksByArtistID(ctx context.Context, artistID uuid.UUID, limit, offset uint64) ([]model.Track, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTracksByArtistID", ctx, artistID, limit, offset)
	ret0, _ := ret[0].([]model.Track)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTracksByArtistID indicates an expected call of GetTracksByArtistID.
func (mr *MockIRepositoryMockRecorder) GetTracksByArtistID(ctx, artistID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTracksByArtistID", reflect.TypeOf((*MockIRepository)(nil).GetTracksByArtistID), ctx, artistID, limit, offset)
}

// GetTracksByGenreID mocks base method.
func (m *MockIRepository) GetTracksByGenreID(ctx context.Context, genreID uuid.UUID, limit, offset uint64) ([]model.Track, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTracksByGenreID", ctx, genreID, limit, offset)
	ret0, _ := ret[0].([]model.Track)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTracksByGenreID indicates an expected call of GetTracksByGenreID.
func (mr *MockIRepositoryMockRecorder) GetTracksByGenreID(ctx, genreID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTracksByGenreID", reflect.TypeOf((*MockIRepository)(nil).GetTracksByGenreID), ctx, genreID, limit, offset)
}

// GetTracksByIDs mocks base method.
func (m *MockIRepository) GetTracksByIDs(ctx context.Context, ids []uuid.UUID) ([]model.Track, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTracksByIDs", ctx, ids)
	ret0, _ := ret[0].([]model.Track)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTracksByIDs indicates an expected call of GetTracksByIDs.
func (mr *MockIRepositoryMockRecorder) GetTracksByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTracksByIDs", reflect.TypeOf((*MockIRepository)(nil).GetTracksByIDs), ctx, ids)
}

// IncrementPlayCount mocks base method.
func (m *MockIRepository) IncrementPlayCount(ctx context.Context, trackID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementPlayCount", ctx, trackID)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementPlayCount indicates an expected call of IncrementPlayCount.
func (mr *MockIRepositoryMockRecorder) IncrementPlayCount(ctx, trackID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementPlayCount", reflect.TypeOf((*MockIRepository)(nil).IncrementPlayCount), ctx, trackID)
}

// SearchAlbums mocks base method.
func (m *MockIRepository) SearchAlbums(ctx context.Context, query string, limit uint64) ([]dto.AlbumSearchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchAlbums", ctx, query, limit)
	ret0, _ := ret[0].([]dto.AlbumSearchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchAlbums indicates an expected call of SearchAlbums.
func (mr *MockIRepositoryMockRecorder) SearchAlbums(ctx, query, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchAlbums", reflect.TypeOf((*MockIRepository)(nil).SearchAlbums), ctx, query, limit)
}

// SearchArtists mocks base method.
func (m *MockIRepository) SearchArtists(ctx context.Context, query string, limit uint64) ([]dto.ArtistSearchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchArtists", ctx, query, limit)
	ret0, _ := ret[0].([]dto.ArtistSearchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchArtists indicates an expected call of SearchArtists.
func (mr *MockIRepositoryMockRecorder) SearchArtists(ctx, query, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchArtists", reflect.TypeOf((*MockIRepository)(nil).SearchArtists), ctx, query, limit)
}

// SearchTracks mocks base method.
func (m *MockIRepository) SearchTracks(ctx context.Context, query string, limit uint64) ([]dto.TrackSearchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchTracks", ctx, query, limit)
	ret0, _ := ret[0].([]dto.TrackSearchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchTracks indicates an expected call of SearchTracks.
func (mr *MockIRepositoryMockRecorder) SearchTracks(ctx, query, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchTracks", reflect.TypeOf((*MockIRepository)(nil).SearchTracks), ctx, query, limit)
}
