// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.20.3
// source: proto/catalog/catalog.proto

package catalog

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Artist struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	HeaderUrl     string                 `protobuf:"bytes,4,opt,name=header_url,json=headerUrl,proto3" json:"header_url,omitempty"`
	Description   *string                `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	PlayCount     int64                  `protobuf:"varint,6,opt,name=play_count,json=playCount,proto3" json:"play_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artist) Reset() {
	*x = Artist{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artist) ProtoMessage() {}

func (x *Artist) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artist.ProtoReflect.Descriptor instead.
func (*Artist) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *Artist) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Artist) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Artist) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *Artist) GetHeaderUrl() string {
	if x != nil {
		return x.HeaderUrl
	}
	return ""
}

func (x *Artist) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Artist) GetPlayCount() int64 {
	if x != nil {
		return x.PlayCount
	}
	return 0
}

type ArtistForAlbum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	HeaderUrl     string                 `protobuf:"bytes,4,opt,name=header_url,json=headerUrl,proto3" json:"header_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtistForAlbum) Reset() {
	*x = ArtistForAlbum{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtistForAlbum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtistForAlbum) ProtoMessage() {}

func (x *ArtistForAlbum) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtistForAlbum.ProtoReflect.Descriptor instead.
func (*ArtistForAlbum) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *ArtistForAlbum) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ArtistForAlbum) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ArtistForAlbum) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *ArtistForAlbum) GetHeaderUrl() string {
	if x != nil {
		return x.HeaderUrl
	}
	return ""
}

type ArtistForTrack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtistForTrack) Reset() {
	*x = ArtistForTrack{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtistForTrack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtistForTrack) ProtoMessage() {}

func (x *ArtistForTrack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtistForTrack.ProtoReflect.Descriptor instead.
func (*ArtistForTrack) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *ArtistForTrack) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ArtistForTrack) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ArtistForTrack) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type Album struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Description   *string                `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	ReleaseDate   string                 `protobuf:"bytes,6,opt,name=release_date,json=releaseDate,proto3" json:"release_date,omitempty"`
	Artists       []*ArtistForAlbum      `protobuf:"bytes,7,rep,name=artists,proto3" json:"artists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Album) Reset() {
	*x = Album{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Album) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Album) ProtoMessage() {}

func (x *Album) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Album.ProtoReflect.Descriptor instead.
func (*Album) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *Album) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Album) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Album) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Album) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *Album) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Album) GetReleaseDate() string {
	if x != nil {
		return x.ReleaseDate
	}
	return ""
}

func (x *Album) GetArtists() []*ArtistForAlbum {
	if x != nil {
		return x.Artists
	}
	return nil
}

type AlbumForTrack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	ReleaseDate   string                 `protobuf:"bytes,4,opt,name=release_date,json=releaseDate,proto3" json:"release_date,omitempty"`
	Artists       []*ArtistForTrack      `protobuf:"bytes,5,rep,name=artists,proto3" json:"artists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlbumForTrack) Reset() {
	*x = AlbumForTrack{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlbumForTrack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlbumForTrack) ProtoMessage() {}

func (x *AlbumForTrack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlbumForTrack.ProtoReflect.Descriptor instead.
func (*AlbumForTrack) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *AlbumForTrack) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AlbumForTrack) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AlbumForTrack) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *AlbumForTrack) GetReleaseDate() string {
	if x != nil {
		return x.ReleaseDate
	}
	return ""
}

func (x *AlbumForTrack) GetArtists() []*ArtistForTrack {
	if x != nil {
		return x.Artists
	}
	return nil
}

type Genre struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Genre) Reset() {
	*x = Genre{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Genre) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Genre) ProtoMessage() {}

func (x *Genre) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Genre.ProtoReflect.Descriptor instead.
func (*Genre) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *Genre) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Genre) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Track struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	DurationS     int32                  `protobuf:"varint,3,opt,name=duration_s,json=durationS,proto3" json:"duration_s,omitempty"`
	FileUrl       string                 `protobuf:"bytes,4,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	PlayCount     int64                  `protobuf:"varint,5,opt,name=play_count,json=playCount,proto3" json:"play_count,omitempty"`
	Artists       []*ArtistForTrack      `protobuf:"bytes,6,rep,name=artists,proto3" json:"artists,omitempty"`
	Album         *AlbumForTrack         `protobuf:"bytes,7,opt,name=album,proto3" json:"album,omitempty"`
	Genres        []*Genre               `protobuf:"bytes,8,rep,name=genres,proto3" json:"genres,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Track) Reset() {
	*x = Track{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Track) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Track) ProtoMessage() {}

func (x *Track) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Track.ProtoReflect.Descriptor instead.
func (*Track) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *Track) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Track) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Track) GetDurationS() int32 {
	if x != nil {
		return x.DurationS
	}
	return 0
}

func (x *Track) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *Track) GetPlayCount() int64 {
	if x != nil {
		return x.PlayCount
	}
	return 0
}

func (x *Track) GetArtists() []*ArtistForTrack {
	if x != nil {
		return x.Artists
	}
	return nil
}

func (x *Track) GetAlbum() *AlbumForTrack {
	if x != nil {
		return x.Album
	}
	return nil
}

func (x *Track) GetGenres() []*Genre {
	if x != nil {
		return x.Genres
	}
	return nil
}

type ArtistSearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artist        *Artist                `protobuf:"bytes,1,opt,name=artist,proto3" json:"artist,omitempty"`
	Rank          float32                `protobuf:"fixed32,2,opt,name=rank,proto3" json:"rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtistSearchResult) Reset() {
	*x = ArtistSearchResult{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtistSearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtistSearchResult) ProtoMessage() {}

func (x *ArtistSearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtistSearchResult.ProtoReflect.Descriptor instead.
func (*ArtistSearchResult) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{7}
}

func (x *ArtistSearchResult) GetArtist() *Artist {
	if x != nil {
		return x.Artist
	}
	return nil
}

func (x *ArtistSearchResult) GetRank() float32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

type AlbumSearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Album         *Album                 `protobuf:"bytes,1,opt,name=album,proto3" json:"album,omitempty"`
	Rank          float32                `protobuf:"fixed32,2,opt,name=rank,proto3" json:"rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlbumSearchResult) Reset() {
	*x = AlbumSearchResult{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlbumSearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlbumSearchResult) ProtoMessage() {}

func (x *AlbumSearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlbumSearchResult.ProtoReflect.Descriptor instead.
func (*AlbumSearchResult) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{8}
}

func (x *AlbumSearchResult) GetAlbum() *Album {
	if x != nil {
		return x.Album
	}
	return nil
}

func (x *AlbumSearchResult) GetRank() float32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

type TrackSearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Track         *Track                 `protobuf:"bytes,1,opt,name=track,proto3" json:"track,omitempty"`
	Rank          float32                `protobuf:"fixed32,2,opt,name=rank,proto3" json:"rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackSearchResult) Reset() {
	*x = TrackSearchResult{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackSearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackSearchResult) ProtoMessage() {}

func (x *TrackSearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackSearchResult.ProtoReflect.Descriptor instead.
func (*TrackSearchResult) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{9}
}

func (x *TrackSearchResult) GetTrack() *Track {
	if x != nil {
		return x.Track
	}
	return nil
}

func (x *TrackSearchResult) GetRank() float32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

type GetArtistByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArtistByIDRequest) Reset() {
	*x = GetArtistByIDRequest{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtistByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtistByIDRequest) ProtoMessage() {}

func (x *GetArtistByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtistByIDRequest.ProtoReflect.Descriptor instead.
func (*GetArtistByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{10}
}

func (x *GetArtistByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAllArtistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         uint64                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllArtistsRequest) Reset() {
	*x = GetAllArtistsRequest{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllArtistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllArtistsRequest) ProtoMessage() {}

func (x *GetAllArtistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllArtistsRequest.ProtoReflect.Descriptor instead.
func (*GetAllArtistsRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{11}
}

func (x *GetAllArtistsRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAllArtistsRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetAllArtistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artists       []*Artist              `protobuf:"bytes,1,rep,name=artists,proto3" json:"artists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllArtistsResponse) Reset() {
	*x = GetAllArtistsResponse{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllArtistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllArtistsResponse) ProtoMessage() {}

func (x *GetAllArtistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllArtistsResponse.ProtoReflect.Descriptor instead.
func (*GetAllArtistsResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{12}
}

func (x *GetAllArtistsResponse) GetArtists() []*Artist {
	if x != nil {
		return x.Artists
	}
	return nil
}

type SearchArtistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         uint64                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchArtistsRequest) Reset() {
	*x = SearchArtistsRequest{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchArtistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchArtistsRequest) ProtoMessage() {}

func (x *SearchArtistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchArtistsRequest.ProtoReflect.Descriptor instead.
func (*SearchArtistsRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{13}
}

func (x *SearchArtistsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchArtistsRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchArtistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ArtistSearchResult  `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchArtistsResponse) Reset() {
	*x = SearchArtistsResponse{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchArtistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchArtistsResponse) ProtoMessage() {}

func (x *SearchArtistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchArtistsResponse.ProtoReflect.Descriptor instead.
func (*SearchArtistsResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{14}
}

func (x *SearchArtistsResponse) GetResults() []*ArtistSearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type GetArtistsByIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArtistsByIDsRequest) Reset() {
	*x = GetArtistsByIDsRequest{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtistsByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtistsByIDsRequest) ProtoMessage() {}

func (x *GetArtistsByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtistsByIDsRequest.ProtoReflect.Descriptor instead.
func (*GetArtistsByIDsRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{15}
}

func (x *GetArtistsByIDsRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetArtistsByIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artists       []*Artist              `protobuf:"bytes,1,rep,name=artists,proto3" json:"artists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArtistsByIDsResponse) Reset() {
	*x = GetArtistsByIDsResponse{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtistsByIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtistsByIDsResponse) ProtoMessage() {}

func (x *GetArtistsByIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtistsByIDsResponse.ProtoReflect.Descriptor instead.
func (*GetArtistsByIDsResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{16}
}

func (x *GetArtistsByIDsResponse) GetArtists() []*Artist {
	if x != nil {
		return x.Artists
	}
	return nil
}

type GetAlbumByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlbumByIDRequest) Reset() {
	*x = GetAlbumByIDRequest{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlbumByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlbumByIDRequest) ProtoMessage() {}

func (x *GetAlbumByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlbumByIDRequest.ProtoReflect.Descriptor instead.
func (*GetAlbumByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{17}
}

func (x *GetAlbumByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAllAlbumsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         uint64                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllAlbumsRequest) Reset() {
	*x = GetAllAlbumsRequest{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllAlbumsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllAlbumsRequest) ProtoMessage() {}

func (x *GetAllAlbumsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllAlbumsRequest.ProtoReflect.Descriptor instead.
func (*GetAllAlbumsRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{18}
}

func (x *GetAllAlbumsRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAllAlbumsRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetAllAlbumsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Albums        []*Album               `protobuf:"bytes,1,rep,name=albums,proto3" json:"albums,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllAlbumsResponse) Reset() {
	*x = GetAllAlbumsResponse{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllAlbumsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllAlbumsResponse) ProtoMessage() {}

func (x *GetAllAlbumsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllAlbumsResponse.ProtoReflect.Descriptor instead.
func (*GetAllAlbumsResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{19}
}

func (x *GetAllAlbumsResponse) GetAlbums() []*Album {
	if x != nil {
		return x.Albums
	}
	return nil
}

type GetAlbumsByArtistIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtistId      string                 `protobuf:"bytes,1,opt,name=artist_id,json=artistId,proto3" json:"artist_id,omitempty"`
	Limit         uint64                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint64                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlbumsByArtistIDRequest) Reset() {
	*x = GetAlbumsByArtistIDRequest{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlbumsByArtistIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlbumsByArtistIDRequest) ProtoMessage() {}

func (x *GetAlbumsByArtistIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlbumsByArtistIDRequest.ProtoReflect.Descriptor instead.
func (*GetAlbumsByArtistIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{20}
}

func (x *GetAlbumsByArtistIDRequest) GetArtistId() string {
	if x != nil {
		return x.ArtistId
	}
	return ""
}

func (x *GetAlbumsByArtistIDRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAlbumsByArtistIDRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type SearchAlbumsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         uint64                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchAlbumsRequest) Reset() {
	*x = SearchAlbumsRequest{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchAlbumsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchAlbumsRequest) ProtoMessage() {}

func (x *SearchAlbumsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchAlbumsRequest.ProtoReflect.Descriptor instead.
func (*SearchAlbumsRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{21}
}

func (x *SearchAlbumsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchAlbumsRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchAlbumsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*AlbumSearchResult   `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchAlbumsResponse) Reset() {
	*x = SearchAlbumsResponse{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchAlbumsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchAlbumsResponse) ProtoMessage() {}

func (x *SearchAlbumsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchAlbumsResponse.ProtoReflect.Descriptor instead.
func (*SearchAlbumsResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{22}
}

func (x *SearchAlbumsResponse) GetResults() []*AlbumSearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type GetAlbumsByIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlbumsByIDsRequest) Reset() {
	*x = GetAlbumsByIDsRequest{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlbumsByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlbumsByIDsRequest) ProtoMessage() {}

func (x *GetAlbumsByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlbumsByIDsRequest.ProtoReflect.Descriptor instead.
func (*GetAlbumsByIDsRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{23}
}

func (x *GetAlbumsByIDsRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetTrackByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrackByIDRequest) Reset() {
	*x = GetTrackByIDRequest{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrackByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrackByIDRequest) ProtoMessage() {}

func (x *GetTrackByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrackByIDRequest.ProtoReflect.Descriptor instead.
func (*GetTrackByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{24}
}

func (x *GetTrackByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAllTracksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         uint64                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllTracksRequest) Reset() {
	*x = GetAllTracksRequest{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllTracksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllTracksRequest) ProtoMessage() {}

func (x *GetAllTracksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllTracksRequest.ProtoReflect.Descriptor instead.
func (*GetAllTracksRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{25}
}

func (x *GetAllTracksRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAllTracksRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetAllTracksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tracks        []*Track               `protobuf:"bytes,1,rep,name=tracks,proto3" json:"tracks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllTracksResponse) Reset() {
	*x = GetAllTracksResponse{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllTracksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllTracksResponse) ProtoMessage() {}

func (x *GetAllTracksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllTracksResponse.ProtoReflect.Descriptor instead.
func (*GetAllTracksResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{26}
}

func (x *GetAllTracksResponse) GetTracks() []*Track {
	if x != nil {
		return x.Tracks
	}
	return nil
}

type GetTracksByArtistIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtistId      string                 `protobuf:"bytes,1,opt,name=artist_id,json=artistId,proto3" json:"artist_id,omitempty"`
	Limit         uint64                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint64                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTracksByArtistIDRequest) Reset() {
	*x = GetTracksByArtistIDRequest{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTracksByArtistIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTracksByArtistIDRequest) ProtoMessage() {}

func (x *GetTracksByArtistIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTracksByArtistIDRequest.ProtoReflect.Descriptor instead.
func (*GetTracksByArtistIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{27}
}

func (x *GetTracksByArtistIDRequest) GetArtistId() string {
	if x != nil {
		return x.ArtistId
	}
	return ""
}

func (x *GetTracksByArtistIDRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetTracksByArtistIDRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetTracksByAlbumIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlbumId       string                 `protobuf:"bytes,1,opt,name=album_id,json=albumId,proto3" json:"album_id,omitempty"`
	Limit         uint64                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint64                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTracksByAlbumIDRequest) Reset() {
	*x = GetTracksByAlbumIDRequest{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTracksByAlbumIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTracksByAlbumIDRequest) ProtoMessage() {}

func (x *GetTracksByAlbumIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTracksByAlbumIDRequest.ProtoReflect.Descriptor instead.
func (*GetTracksByAlbumIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{28}
}

func (x *GetTracksByAlbumIDRequest) GetAlbumId() string {
	if x != nil {
		return x.AlbumId
	}
	return ""
}

func (x *GetTracksByAlbumIDRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetTracksByAlbumIDRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetTracksByGenreIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GenreId       string                 `protobuf:"bytes,1,opt,name=genre_id,json=genreId,proto3" json:"genre_id,omitempty"`
	Limit         uint64                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint64                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTracksByGenreIDRequest) Reset() {
	*x = GetTracksByGenreIDRequest{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTracksByGenreIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTracksByGenreIDRequest) ProtoMessage() {}

func (x *GetTracksByGenreIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTracksByGenreIDRequest.ProtoReflect.Descriptor instead.
func (*GetTracksByGenreIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{29}
}

func (x *GetTracksByGenreIDRequest) GetGenreId() string {
	if x != nil {
		return x.GenreId
	}
	return ""
}

func (x *GetTracksByGenreIDRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetTracksByGenreIDRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type SearchTracksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         uint64                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTracksRequest) Reset() {
	*x = SearchTracksRequest{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTracksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTracksRequest) ProtoMessage() {}

func (x *SearchTracksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTracksRequest.ProtoReflect.Descriptor instead.
func (*SearchTracksRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{30}
}

func (x *SearchTracksRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchTracksRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchTracksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*TrackSearchResult   `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTracksResponse) Reset() {
	*x = SearchTracksResponse{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTracksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTracksResponse) ProtoMessage() {}

func (x *SearchTracksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTracksResponse.ProtoReflect.Descriptor instead.
func (*SearchTracksResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{31}
}

func (x *SearchTracksResponse) GetResults() []*TrackSearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type RegisterPlayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackId       string                 `protobuf:"bytes,1,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterPlayRequest) Reset() {
	*x = RegisterPlayRequest{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPlayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPlayRequest) ProtoMessage() {}

func (x *RegisterPlayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPlayRequest.ProtoReflect.Descriptor instead.
func (*RegisterPlayRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{32}
}

func (x *RegisterPlayRequest) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

type RegisterPlayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterPlayResponse) Reset() {
	*x = RegisterPlayResponse{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPlayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPlayResponse) ProtoMessage() {}

func (x *RegisterPlayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPlayResponse.ProtoReflect.Descriptor instead.
func (*RegisterPlayResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{33}
}

type GetTracksByIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTracksByIDsRequest) Reset() {
	*x = GetTracksByIDsRequest{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTracksByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTracksByIDsRequest) ProtoMessage() {}

func (x *GetTracksByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTracksByIDsRequest.ProtoReflect.Descriptor instead.
func (*GetTracksByIDsRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{34}
}

func (x *GetTracksByIDsRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetTracksByIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tracks        []*Track               `protobuf:"bytes,1,rep,name=tracks,proto3" json:"tracks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTracksByIDsResponse) Reset() {
	*x = GetTracksByIDsResponse{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTracksByIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTracksByIDsResponse) ProtoMessage() {}

func (x *GetTracksByIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTracksByIDsResponse.ProtoReflect.Descriptor instead.
func (*GetTracksByIDsResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{35}
}

func (x *GetTracksByIDsResponse) GetTracks() []*Track {
	if x != nil {
		return x.Tracks
	}
	return nil
}

var File_proto_catalog_catalog_proto protoreflect.FileDescriptor

const file_proto_catalog_catalog_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/catalog/catalog.proto\x12\acatalog\"\xc0\x01\n" +
	"\x06Artist\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x12\x1d\n" +
	"\n" +
	"header_url\x18\x04 \x01(\tR\theaderUrl\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"play_count\x18\x06 \x01(\x03R\tplayCountB\x0e\n" +
	"\f_description\"r\n" +
	"\x0eArtistForAlbum\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x12\x1d\n" +
	"\n" +
	"header_url\x18\x04 \x01(\tR\theaderUrl\"S\n" +
	"\x0eArtistForTrack\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\"\xed\x01\n" +
	"\x05Album\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x00R\vdescription\x88\x01\x01\x12!\n" +
	"\frelease_date\x18\x06 \x01(\tR\vreleaseDate\x121\n" +
	"\aartists\x18\a \x03(\v2\x17.catalog.ArtistForAlbumR\aartistsB\x0e\n" +
	"\f_description\"\xaa\x01\n" +
	"\rAlbumForTrack\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x12!\n" +
	"\frelease_date\x18\x04 \x01(\tR\vreleaseDate\x121\n" +
	"\aartists\x18\x05 \x03(\v2\x17.catalog.ArtistForTrackR\aartists\"+\n" +
	"\x05Genre\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x8f\x02\n" +
	"\x05Track\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"duration_s\x18\x03 \x01(\x05R\tdurationS\x12\x19\n" +
	"\bfile_url\x18\x04 \x01(\tR\afileUrl\x12\x1d\n" +
	"\n" +
	"play_count\x18\x05 \x01(\x03R\tplayCount\x121\n" +
	"\aartists\x18\x06 \x03(\v2\x17.catalog.ArtistForTrackR\aartists\x12,\n" +
	"\x05album\x18\a \x01(\v2\x16.catalog.AlbumForTrackR\x05album\x12&\n" +
	"\x06genres\x18\b \x03(\v2\x0e.catalog.GenreR\x06genres\"Q\n" +
	"\x12ArtistSearchResult\x12'\n" +
	"\x06artist\x18\x01 \x01(\v2\x0f.catalog.ArtistR\x06artist\x12\x12\n" +
	"\x04rank\x18\x02 \x01(\x02R\x04rank\"M\n" +
	"\x11AlbumSearchResult\x12$\n" +
	"\x05album\x18\x01 \x01(\v2\x0e.catalog.AlbumR\x05album\x12\x12\n" +
	"\x04rank\x18\x02 \x01(\x02R\x04rank\"M\n" +
	"\x11TrackSearchResult\x12$\n" +
	"\x05track\x18\x01 \x01(\v2\x0e.catalog.TrackR\x05track\x12\x12\n" +
	"\x04rank\x18\x02 \x01(\x02R\x04rank\"&\n" +
	"\x14GetArtistByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"D\n" +
	"\x14GetAllArtistsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x04R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\"B\n" +
	"\x15GetAllArtistsResponse\x12)\n" +
	"\aartists\x18\x01 \x03(\v2\x0f.catalog.ArtistR\aartists\"B\n" +
	"\x14SearchArtistsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x04R\x05limit\"N\n" +
	"\x15SearchArtistsResponse\x125\n" +
	"\aresults\x18\x01 \x03(\v2\x1b.catalog.ArtistSearchResultR\aresults\"*\n" +
	"\x16GetArtistsByIDsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"D\n" +
	"\x17GetArtistsByIDsResponse\x12)\n" +
	"\aartists\x18\x01 \x03(\v2\x0f.catalog.ArtistR\aartists\"%\n" +
	"\x13GetAlbumByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"C\n" +
	"\x13GetAllAlbumsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x04R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\">\n" +
	"\x14GetAllAlbumsResponse\x12&\n" +
	"\x06albums\x18\x01 \x03(\v2\x0e.catalog.AlbumR\x06albums\"g\n" +
	"\x1aGetAlbumsByArtistIDRequest\x12\x1b\n" +
	"\tartist_id\x18\x01 \x01(\tR\bartistId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x04R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x04R\x06offset\"A\n" +
	"\x13SearchAlbumsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x04R\x05limit\"L\n" +
	"\x14SearchAlbumsResponse\x124\n" +
	"\aresults\x18\x01 \x03(\v2\x1a.catalog.AlbumSearchResultR\aresults\")\n" +
	"\x15GetAlbumsByIDsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"%\n" +
	"\x13GetTrackByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"C\n" +
	"\x13GetAllTracksRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x04R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\">\n" +
	"\x14GetAllTracksResponse\x12&\n" +
	"\x06tracks\x18\x01 \x03(\v2\x0e.catalog.TrackR\x06tracks\"g\n" +
	"\x1aGetTracksByArtistIDRequest\x12\x1b\n" +
	"\tartist_id\x18\x01 \x01(\tR\bartistId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x04R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x04R\x06offset\"d\n" +
	"\x19GetTracksByAlbumIDRequest\x12\x19\n" +
	"\balbum_id\x18\x01 \x01(\tR\aalbumId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x04R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x04R\x06offset\"d\n" +
	"\x19GetTracksByGenreIDRequest\x12\x19\n" +
	"\bgenre_id\x18\x01 \x01(\tR\agenreId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x04R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x04R\x06offset\"A\n" +
	"\x13SearchTracksRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x04R\x05limit\"L\n" +
	"\x14SearchTracksResponse\x124\n" +
	"\aresults\x18\x01 \x03(\v2\x1a.catalog.TrackSearchResultR\aresults\"0\n" +
	"\x13RegisterPlayRequest\x12\x19\n" +
	"\btrack_id\x18\x01 \x01(\tR\atrackId\"\x16\n" +
	"\x14RegisterPlayResponse\")\n" +
	"\x15GetTracksByIDsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"@\n" +
	"\x16GetTracksByIDsResponse\x12&\n" +
	"\x06tracks\x18\x01 \x03(\v2\x0e.catalog.TrackR\x06tracks2\x98\n" +
	"\n" +
	"\x0eCatalogService\x12A\n" +
	"\rGetArtistByID\x12\x1d.catalog.GetArtistByIDRequest\x1a\x0f.catalog.Artist\"\x00\x12P\n" +
	"\rGetAllArtists\x12\x1d.catalog.GetAllArtistsRequest\x1a\x1e.catalog.GetAllArtistsResponse\"\x00\x12P\n" +
	"\rSearchArtists\x12\x1d.catalog.SearchArtistsRequest\x1a\x1e.catalog.SearchArtistsResponse\"\x00\x12Q\n" +
	"\x0eGetTracksByIDs\x12\x1e.catalog.GetTracksByIDsRequest\x1a\x1f.catalog.GetTracksByIDsResponse\x12>\n" +
	"\fGetAlbumByID\x12\x1c.catalog.GetAlbumByIDRequest\x1a\x0e.catalog.Album\"\x00\x12M\n" +
	"\fGetAllAlbums\x12\x1c.catalog.GetAllAlbumsRequest\x1a\x1d.catalog.GetAllAlbumsResponse\"\x00\x12[\n" +
	"\x13GetAlbumsByArtistID\x12#.catalog.GetAlbumsByArtistIDRequest\x1a\x1d.catalog.GetAllAlbumsResponse\"\x00\x12M\n" +
	"\fSearchAlbums\x12\x1c.catalog.SearchAlbumsRequest\x1a\x1d.catalog.SearchAlbumsResponse\"\x00\x12Q\n" +
	"\x0eGetAlbumsByIDs\x12\x1e.catalog.GetAlbumsByIDsRequest\x1a\x1d.catalog.GetAllAlbumsResponse\"\x00\x12>\n" +
	"\fGetTrackByID\x12\x1c.catalog.GetTrackByIDRequest\x1a\x0e.catalog.Track\"\x00\x12M\n" +
	"\fGetAllTracks\x12\x1c.catalog.GetAllTracksRequest\x1a\x1d.catalog.GetAllTracksResponse\"\x00\x12[\n" +
	"\x13GetTracksByArtistID\x12#.catalog.GetTracksByArtistIDRequest\x1a\x1d.catalog.GetAllTracksResponse\"\x00\x12Y\n" +
	"\x12GetTracksByAlbumID\x12\".catalog.GetTracksByAlbumIDRequest\x1a\x1d.catalog.GetAllTracksResponse\"\x00\x12Y\n" +
	"\x12GetTracksByGenreID\x12\".catalog.GetTracksByGenreIDRequest\x1a\x1d.catalog.GetAllTracksResponse\"\x00\x12M\n" +
	"\fSearchTracks\x12\x1c.catalog.SearchTracksRequest\x1a\x1d.catalog.SearchTracksResponse\"\x00\x12M\n" +
	"\fRegisterPlay\x12\x1c.catalog.RegisterPlayRequest\x1a\x1d.catalog.RegisterPlayResponse\"\x00B\x17Z\x15spotify/proto/catalogb\x06proto3"

var (
	file_proto_catalog_catalog_proto_rawDescOnce sync.Once
	file_proto_catalog_catalog_proto_rawDescData []byte
)

func file_proto_catalog_catalog_proto_rawDescGZIP() []byte {
	file_proto_catalog_catalog_proto_rawDescOnce.Do(func() {
		file_proto_catalog_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_catalog_catalog_proto_rawDesc), len(file_proto_catalog_catalog_proto_rawDesc)))
	})
	return file_proto_catalog_catalog_proto_rawDescData
}

var file_proto_catalog_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_proto_catalog_catalog_proto_goTypes = []any{
	(*Artist)(nil),                     // 0: catalog.Artist
	(*ArtistForAlbum)(nil),             // 1: catalog.ArtistForAlbum
	(*ArtistForTrack)(nil),             // 2: catalog.ArtistForTrack
	(*Album)(nil),                      // 3: catalog.Album
	(*AlbumForTrack)(nil),              // 4: catalog.AlbumForTrack
	(*Genre)(nil),                      // 5: catalog.Genre
	(*Track)(nil),                      // 6: catalog.Track
	(*ArtistSearchResult)(nil),         // 7: catalog.ArtistSearchResult
	(*AlbumSearchResult)(nil),          // 8: catalog.AlbumSearchResult
	(*TrackSearchResult)(nil),          // 9: catalog.TrackSearchResult
	(*GetArtistByIDRequest)(nil),       // 10: catalog.GetArtistByIDRequest
	(*GetAllArtistsRequest)(nil),       // 11: catalog.GetAllArtistsRequest
	(*GetAllArtistsResponse)(nil),      // 12: catalog.GetAllArtistsResponse
	(*SearchArtistsRequest)(nil),       // 13: catalog.SearchArtistsRequest
	(*SearchArtistsResponse)(nil),      // 14: catalog.SearchArtistsResponse
	(*GetArtistsByIDsRequest)(nil),     // 15: catalog.GetArtistsByIDsRequest
	(*GetArtistsByIDsResponse)(nil),    // 16: catalog.GetArtistsByIDsResponse
	(*GetAlbumByIDRequest)(nil),        // 17: catalog.GetAlbumByIDRequest
	(*GetAllAlbumsRequest)(nil),        // 18: catalog.GetAllAlbumsRequest
	(*GetAllAlbumsResponse)(nil),       // 19: catalog.GetAllAlbumsResponse
	(*GetAlbumsByArtistIDRequest)(nil), // 20: catalog.GetAlbumsByArtistIDRequest
	(*SearchAlbumsRequest)(nil),        // 21: catalog.SearchAlbumsRequest
	(*SearchAlbumsResponse)(nil),       // 22: catalog.SearchAlbumsResponse
	(*GetAlbumsByIDsRequest)(nil),      // 23: catalog.GetAlbumsByIDsRequest
	(*GetTrackByIDRequest)(nil),        // 24: catalog.GetTrackByIDRequest
	(*GetAllTracksRequest)(nil),        // 25: catalog.GetAllTracksRequest
	(*GetAllTracksResponse)(nil),       // 26: catalog.GetAllTracksResponse
	(*GetTracksByArtistIDRequest)(nil), // 27: catalog.GetTracksByArtistIDRequest
	(*GetTracksByAlbumIDRequest)(nil),  // 28: catalog.GetTracksByAlbumIDRequest
	(*GetTracksByGenreIDRequest)(nil),  // 29: catalog.GetTracksByGenreIDRequest
	(*SearchTracksRequest)(nil),        // 30: catalog.SearchTracksRequest
	(*SearchTracksResponse)(nil),       // 31: catalog.SearchTracksResponse
	(*RegisterPlayRequest)(nil),        // 32: catalog.RegisterPlayRequest
	(*RegisterPlayResponse)(nil),       // 33: catalog.RegisterPlayResponse
	(*GetTracksByIDsRequest)(nil),      // 34: catalog.GetTracksByIDsRequest
	(*GetTracksByIDsResponse)(nil),     // 35: catalog.GetTracksByIDsResponse
}
var file_proto_catalog_catalog_proto_depIdxs = []int32{
	1,  // 0: catalog.Album.artists:type_name -> catalog.ArtistForAlbum
	2,  // 1: catalog.AlbumForTrack.artists:type_name -> catalog.ArtistForTrack
	2,  // 2: catalog.Track.artists:type_name -> catalog.ArtistForTrack
	4,  // 3: catalog.Track.album:type_name -> catalog.AlbumForTrack
	5,  // 4: catalog.Track.genres:type_name -> catalog.Genre
	0,  // 5: catalog.ArtistSearchResult.artist:type_name -> catalog.Artist
	3,  // 6: catalog.AlbumSearchResult.album:type_name -> catalog.Album
	6,  // 7: catalog.TrackSearchResult.track:type_name -> catalog.Track
	0,  // 8: catalog.GetAllArtistsResponse.artists:type_name -> catalog.Artist
	7,  // 9: catalog.SearchArtistsResponse.results:type_name -> catalog.ArtistSearchResult
	0,  // 10: catalog.GetArtistsByIDsResponse.artists:type_name -> catalog.Artist
	3,  // 11: catalog.GetAllAlbumsResponse.albums:type_name -> catalog.Album
	8,  // 12: catalog.SearchAlbumsResponse.results:type_name -> catalog.AlbumSearchResult
	6,  // 13: catalog.GetAllTracksResponse.tracks:type_name -> catalog.Track
	9,  // 14: catalog.SearchTracksResponse.results:type_name -> catalog.TrackSearchResult
	6,  // 15: catalog.GetTracksByIDsResponse.tracks:type_name -> catalog.Track
	10, // 16: catalog.CatalogService.GetArtistByID:input_type -> catalog.GetArtistByIDRequest
	11, // 17: catalog.CatalogService.GetAllArtists:input_type -> catalog.GetAllArtistsRequest
	13, // 18: catalog.CatalogService.SearchArtists:input_type -> catalog.SearchArtistsRequest
	34, // 19: catalog.CatalogService.GetTracksByIDs:input_type -> catalog.GetTracksByIDsRequest
	17, // 20: catalog.CatalogService.GetAlbumByID:input_type -> catalog.GetAlbumByIDRequest
	18, // 21: catalog.CatalogService.GetAllAlbums:input_type -> catalog.GetAllAlbumsRequest
	20, // 22: catalog.CatalogService.GetAlbumsByArtistID:input_type -> catalog.GetAlbumsByArtistIDRequest
	21, // 23: catalog.CatalogService.SearchAlbums:input_type -> catalog.SearchAlbumsRequest
	23, // 24: catalog.CatalogService.GetAlbumsByIDs:input_type -> catalog.GetAlbumsByIDsRequest
	24, // 25: catalog.CatalogService.GetTrackByID:input_type -> catalog.GetTrackByIDRequest
	25, // 26: catalog.CatalogService.GetAllTracks:input_type -> catalog.GetAllTracksRequest
	27, // 27: catalog.CatalogService.GetTracksByArtistID:input_type -> catalog.GetTracksByArtistIDRequest
	28, // 28: catalog.CatalogService.GetTracksByAlbumID:input_type -> catalog.GetTracksByAlbumIDRequest
	29, // 29: catalog.CatalogService.GetTracksByGenreID:input_type -> catalog.GetTracksByGenreIDRequest
	30, // 30: catalog.CatalogService.SearchTracks:input_type -> catalog.SearchTracksRequest
	32, // 31: catalog.CatalogService.RegisterPlay:input_type -> catalog.RegisterPlayRequest
	0,  // 32: catalog.CatalogService.GetArtistByID:output_type -> catalog.Artist
	12, // 33: catalog.CatalogService.GetAllArtists:output_type -> catalog.GetAllArtistsResponse
	14, // 34: catalog.CatalogService.SearchArtists:output_type -> catalog.SearchArtistsResponse
	35, // 35: catalog.CatalogService.GetTracksByIDs:output_type -> catalog.GetTracksByIDsResponse
	3,  // 36: catalog.CatalogService.GetAlbumByID:output_type -> catalog.Album
	19, // 37: catalog.CatalogService.GetAllAlbums:output_type -> catalog.GetAllAlbumsResponse
	19, // 38: catalog.CatalogService.GetAlbumsByArtistID:output_type -> catalog.GetAllAlbumsResponse
	22, // 39: catalog.CatalogService.SearchAlbums:output_type -> catalog.SearchAlbumsResponse
	19, // 40: catalog.CatalogService.GetAlbumsByIDs:output_type -> catalog.GetAllAlbumsResponse
	6,  // 41: catalog.CatalogService.GetTrackByID:output_type -> catalog.Track
	26, // 42: catalog.CatalogService.GetAllTracks:output_type -> catalog.GetAllTracksResponse
	26, // 43: catalog.CatalogService.GetTracksByArtistID:output_type -> catalog.GetAllTracksResponse
	26, // 44: catalog.CatalogService.GetTracksByAlbumID:output_type -> catalog.GetAllTracksResponse
	26, // 45: catalog.CatalogService.GetTracksByGenreID:output_type -> catalog.GetAllTracksResponse
	31, // 46: catalog.CatalogService.SearchTracks:output_type -> catalog.SearchTracksResponse
	33, // 47: catalog.CatalogService.RegisterPlay:output_type -> catalog.RegisterPlayResponse
	32, // [32:48] is the sub-list for method output_type
	16, // [16:32] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_proto_catalog_catalog_proto_init() }
func file_proto_catalog_catalog_proto_init() {
	if File_proto_catalog_catalog_proto != nil {
		return
	}
	file_proto_catalog_catalog_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_catalog_catalog_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_catalog_catalog_proto_rawDesc), len(file_proto_catalog_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_catalog_catalog_proto_goTypes,
		DependencyIndexes: file_proto_catalog_catalog_proto_depIdxs,
		MessageInfos:      file_proto_catalog_catalog_proto_msgTypes,
	}.Build()
	File_proto_catalog_catalog_proto = out.File
	file_proto_catalog_catalog_proto_goTypes = nil
	file_proto_catalog_catalog_proto_depIdxs = nil
}
