// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.3
// source: proto/catalog/catalog.proto

package catalog

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CatalogService_GetArtistByID_FullMethodName       = "/catalog.CatalogService/GetArtistByID"
	CatalogService_GetAllArtists_FullMethodName       = "/catalog.CatalogService/GetAllArtists"
	CatalogService_SearchArtists_FullMethodName       = "/catalog.CatalogService/SearchArtists"
	CatalogService_GetArtistsByIDs_FullMethodName     = "/catalog.CatalogService/GetArtistsByIDs"
	CatalogService_GetTracksByIDs_FullMethodName      = "/catalog.CatalogService/GetTracksByIDs"
	CatalogService_GetAlbumByID_FullMethodName        = "/catalog.CatalogService/GetAlbumByID"
	CatalogService_GetAllAlbums_FullMethodName        = "/catalog.CatalogService/GetAllAlbums"
	CatalogService_GetAlbumsByArtistID_FullMethodName = "/catalog.CatalogService/GetAlbumsByArtistID"
	CatalogService_SearchAlbums_FullMethodName        = "/catalog.CatalogService/SearchAlbums"
	CatalogService_GetAlbumsByIDs_FullMethodName      = "/catalog.CatalogService/GetAlbumsByIDs"
	CatalogService_GetTrackByID_FullMethodName        = "/catalog.CatalogService/GetTrackByID"
	CatalogService_GetAllTracks_FullMethodName        = "/catalog.CatalogService/GetAllTracks"
	CatalogService_GetTracksByArtistID_FullMethodName = "/catalog.CatalogService/GetTracksByArtistID"
	CatalogService_GetTracksByAlbumID_FullMethodName  = "/catalog.CatalogService/GetTracksByAlbumID"
	CatalogService_GetTracksByGenreID_FullMethodName  = "/catalog.CatalogService/GetTracksByGenreID"
	CatalogService_SearchTracks_FullMethodName        = "/catalog.CatalogService/SearchTracks"
	CatalogService_RegisterPlay_FullMethodName        = "/catalog.CatalogService/RegisterPlay"
)

// CatalogServiceClient is the client API for CatalogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CatalogServiceClient interface {
	GetArtistByID(ctx context.Context, in *GetArtistByIDRequest, opts ...grpc.CallOption) (*Artist, error)
	GetAllArtists(ctx context.Context, in *GetAllArtistsRequest, opts ...grpc.CallOption) (*GetAllArtistsResponse, error)
	SearchArtists(ctx context.Context, in *SearchArtistsRequest, opts ...grpc.CallOption) (*SearchArtistsResponse, error)
	GetArtistsByIDs(ctx context.Context, in *GetArtistsByIDsRequest, opts ...grpc.CallOption) (*GetArtistsByIDsResponse, error)
	GetTracksByIDs(ctx context.Context, in *GetTracksByIDsRequest, opts ...grpc.CallOption) (*GetTracksByIDsResponse, error)
	GetAlbumByID(ctx context.Context, in *GetAlbumByIDRequest, opts ...grpc.CallOption) (*Album, error)
	GetAllAlbums(ctx context.Context, in *GetAllAlbumsRequest, opts ...grpc.CallOption) (*GetAllAlbumsResponse, error)
	GetAlbumsByArtistID(ctx context.Context, in *GetAlbumsByArtistIDRequest, opts ...grpc.CallOption) (*GetAllAlbumsResponse, error)
	SearchAlbums(ctx context.Context, in *SearchAlbumsRequest, opts ...grpc.CallOption) (*SearchAlbumsResponse, error)
	GetAlbumsByIDs(ctx context.Context, in *GetAlbumsByIDsRequest, opts ...grpc.CallOption) (*GetAllAlbumsResponse, error)
	GetTrackByID(ctx context.Context, in *GetTrackByIDRequest, opts ...grpc.CallOption) (*Track, error)
	GetAllTracks(ctx context.Context, in *GetAllTracksRequest, opts ...grpc.CallOption) (*GetAllTracksResponse, error)
	GetTracksByArtistID(ctx context.Context, in *GetTracksByArtistIDRequest, opts ...grpc.CallOption) (*GetAllTracksResponse, error)
	GetTracksByAlbumID(ctx context.Context, in *GetTracksByAlbumIDRequest, opts ...grpc.CallOption) (*GetAllTracksResponse, error)
	GetTracksByGenreID(ctx context.Context, in *GetTracksByGenreIDRequest, opts ...grpc.CallOption) (*GetAllTracksResponse, error)
	SearchTracks(ctx context.Context, in *SearchTracksRequest, opts ...grpc.CallOption) (*SearchTracksResponse, error)
	RegisterPlay(ctx context.Context, in *RegisterPlayRequest, opts ...grpc.CallOption) (*RegisterPlayResponse, error)
}

type catalogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCatalogServiceClient(cc grpc.ClientConnInterface) CatalogServiceClient {
	return &catalogServiceClient{cc}
}

func (c *catalogServiceClient) GetArtistByID(ctx context.Context, in *GetArtistByIDRequest, opts ...grpc.CallOption) (*Artist, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Artist)
	err := c.cc.Invoke(ctx, CatalogService_GetArtistByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetAllArtists(ctx context.Context, in *GetAllArtistsRequest, opts ...grpc.CallOption) (*GetAllArtistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllArtistsResponse)
	err := c.cc.Invoke(ctx, CatalogService_GetAllArtists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) SearchArtists(ctx context.Context, in *SearchArtistsRequest, opts ...grpc.CallOption) (*SearchArtistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchArtistsResponse)
	err := c.cc.Invoke(ctx, CatalogService_SearchArtists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetArtistsByIDs(ctx context.Context, in *GetArtistsByIDsRequest, opts ...grpc.CallOption) (*GetArtistsByIDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetArtistsByIDsResponse)
	err := c.cc.Invoke(ctx, CatalogService_GetArtistsByIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetTracksByIDs(ctx context.Context, in *GetTracksByIDsRequest, opts ...grpc.CallOption) (*GetTracksByIDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTracksByIDsResponse)
	err := c.cc.Invoke(ctx, CatalogService_GetTracksByIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetAlbumByID(ctx context.Context, in *GetAlbumByIDRequest, opts ...grpc.CallOption) (*Album, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Album)
	err := c.cc.Invoke(ctx, CatalogService_GetAlbumByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetAllAlbums(ctx context.Context, in *GetAllAlbumsRequest, opts ...grpc.CallOption) (*GetAllAlbumsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllAlbumsResponse)
	err := c.cc.Invoke(ctx, CatalogService_GetAllAlbums_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetAlbumsByArtistID(ctx context.Context, in *GetAlbumsByArtistIDRequest, opts ...grpc.CallOption) (*GetAllAlbumsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllAlbumsResponse)
	err := c.cc.Invoke(ctx, CatalogService_GetAlbumsByArtistID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) SearchAlbums(ctx context.Context, in *SearchAlbumsRequest, opts ...grpc.CallOption) (*SearchAlbumsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchAlbumsResponse)
	err := c.cc.Invoke(ctx, CatalogService_SearchAlbums_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetAlbumsByIDs(ctx context.Context, in *GetAlbumsByIDsRequest, opts ...grpc.CallOption) (*GetAllAlbumsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllAlbumsResponse)
	err := c.cc.Invoke(ctx, CatalogService_GetAlbumsByIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetTrackByID(ctx context.Context, in *GetTrackByIDRequest, opts ...grpc.CallOption) (*Track, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Track)
	err := c.cc.Invoke(ctx, CatalogService_GetTrackByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetAllTracks(ctx context.Context, in *GetAllTracksRequest, opts ...grpc.CallOption) (*GetAllTracksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllTracksResponse)
	err := c.cc.Invoke(ctx, CatalogService_GetAllTracks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetTracksByArtistID(ctx context.Context, in *GetTracksByArtistIDRequest, opts ...grpc.CallOption) (*GetAllTracksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllTracksResponse)
	err := c.cc.Invoke(ctx, CatalogService_GetTracksByArtistID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetTracksByAlbumID(ctx context.Context, in *GetTracksByAlbumIDRequest, opts ...grpc.CallOption) (*GetAllTracksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllTracksResponse)
	err := c.cc.Invoke(ctx, CatalogService_GetTracksByAlbumID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetTracksByGenreID(ctx context.Context, in *GetTracksByGenreIDRequest, opts ...grpc.CallOption) (*GetAllTracksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllTracksResponse)
	err := c.cc.Invoke(ctx, CatalogService_GetTracksByGenreID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) SearchTracks(ctx context.Context, in *SearchTracksRequest, opts ...grpc.CallOption) (*SearchTracksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchTracksResponse)
	err := c.cc.Invoke(ctx, CatalogService_SearchTracks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) RegisterPlay(ctx context.Context, in *RegisterPlayRequest, opts ...grpc.CallOption) (*RegisterPlayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterPlayResponse)
	err := c.cc.Invoke(ctx, CatalogService_RegisterPlay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatalogServiceServer is the server API for CatalogService service.
// All implementations must embed UnimplementedCatalogServiceServer
// for forward compatibility.
type CatalogServiceServer interface {
	GetArtistByID(context.Context, *GetArtistByIDRequest) (*Artist, error)
	GetAllArtists(context.Context, *GetAllArtistsRequest) (*GetAllArtistsResponse, error)
	SearchArtists(context.Context, *SearchArtistsRequest) (*SearchArtistsResponse, error)
	GetArtistsByIDs(context.Context, *GetArtistsByIDsRequest) (*GetArtistsByIDsResponse, error)
	GetTracksByIDs(context.Context, *GetTracksByIDsRequest) (*GetTracksByIDsResponse, error)
	GetAlbumByID(context.Context, *GetAlbumByIDRequest) (*Album, error)
	GetAllAlbums(context.Context, *GetAllAlbumsRequest) (*GetAllAlbumsResponse, error)
	GetAlbumsByArtistID(context.Context, *GetAlbumsByArtistIDRequest) (*GetAllAlbumsResponse, error)
	SearchAlbums(context.Context, *SearchAlbumsRequest) (*SearchAlbumsResponse, error)
	GetAlbumsByIDs(context.Context, *GetAlbumsByIDsRequest) (*GetAllAlbumsResponse, error)
	GetTrackByID(context.Context, *GetTrackByIDRequest) (*Track, error)
	GetAllTracks(context.Context, *GetAllTracksRequest) (*GetAllTracksResponse, error)
	GetTracksByArtistID(context.Context, *GetTracksByArtistIDRequest) (*GetAllTracksResponse, error)
	GetTracksByAlbumID(context.Context, *GetTracksByAlbumIDRequest) (*GetAllTracksResponse, error)
	GetTracksByGenreID(context.Context, *GetTracksByGenreIDRequest) (*GetAllTracksResponse, error)
	SearchTracks(context.Context, *SearchTracksRequest) (*SearchTracksResponse, error)
	RegisterPlay(context.Context, *RegisterPlayRequest) (*RegisterPlayResponse, error)
	mustEmbedUnimplementedCatalogServiceServer()
}

// UnimplementedCatalogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCatalogServiceServer struct{}

func (UnimplementedCatalogServiceServer) GetArtistByID(context.Context, *GetArtistByIDRequest) (*Artist, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArtistByID not implemented")
}
func (UnimplementedCatalogServiceServer) GetAllArtists(context.Context, *GetAllArtistsRequest) (*GetAllArtistsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllArtists not implemented")
}
func (UnimplementedCatalogServiceServer) SearchArtists(context.Context, *SearchArtistsRequest) (*SearchArtistsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchArtists not implemented")
}
func (UnimplementedCatalogServiceServer) GetArtistsByIDs(context.Context, *GetArtistsByIDsRequest) (*GetArtistsByIDsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArtistsByIDs not implemented")
}
func (UnimplementedCatalogServiceServer) GetTracksByIDs(context.Context, *GetTracksByIDsRequest) (*GetTracksByIDsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTracksByIDs not implemented")
}
func (UnimplementedCatalogServiceServer) GetAlbumByID(context.Context, *GetAlbumByIDRequest) (*Album, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAlbumByID not implemented")
}
func (UnimplementedCatalogServiceServer) GetAllAlbums(context.Context, *GetAllAlbumsRequest) (*GetAllAlbumsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllAlbums not implemented")
}
func (UnimplementedCatalogServiceServer) GetAlbumsByArtistID(context.Context, *GetAlbumsByArtistIDRequest) (*GetAllAlbumsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAlbumsByArtistID not implemented")
}
func (UnimplementedCatalogServiceServer) SearchAlbums(context.Context, *SearchAlbumsRequest) (*SearchAlbumsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchAlbums not implemented")
}
func (UnimplementedCatalogServiceServer) GetAlbumsByIDs(context.Context, *GetAlbumsByIDsRequest) (*GetAllAlbumsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAlbumsByIDs not implemented")
}
func (UnimplementedCatalogServiceServer) GetTrackByID(context.Context, *GetTrackByIDRequest) (*Track, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrackByID not implemented")
}
func (UnimplementedCatalogServiceServer) GetAllTracks(context.Context, *GetAllTracksRequest) (*GetAllTracksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllTracks not implemented")
}
func (UnimplementedCatalogServiceServer) GetTracksByArtistID(context.Context, *GetTracksByArtistIDRequest) (*GetAllTracksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTracksByArtistID not implemented")
}
func (UnimplementedCatalogServiceServer) GetTracksByAlbumID(context.Context, *GetTracksByAlbumIDRequest) (*GetAllTracksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTracksByAlbumID not implemented")
}
func (UnimplementedCatalogServiceServer) GetTracksByGenreID(context.Context, *GetTracksByGenreIDRequest) (*GetAllTracksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTracksByGenreID not implemented")
}
func (UnimplementedCatalogServiceServer) SearchTracks(context.Context, *SearchTracksRequest) (*SearchTracksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchTracks not implemented")
}
func (UnimplementedCatalogServiceServer) RegisterPlay(context.Context, *RegisterPlayRequest) (*RegisterPlayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterPlay not implemented")
}
func (UnimplementedCatalogServiceServer) mustEmbedUnimplementedCatalogServiceServer() {}
func (UnimplementedCatalogServiceServer) testEmbeddedByValue()                        {}

// UnsafeCatalogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatalogServiceServer will
// result in compilation errors.
type UnsafeCatalogServiceServer interface {
	mustEmbedUnimplementedCatalogServiceServer()
}

func RegisterCatalogServiceServer(s grpc.ServiceRegistrar, srv CatalogServiceServer) {
	// If the following call pancis, it indicates UnimplementedCatalogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CatalogService_ServiceDesc, srv)
}

func _CatalogService_GetArtistByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArtistByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetArtistByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetArtistByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetArtistByID(ctx, req.(*GetArtistByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetAllArtists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllArtistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetAllArtists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetAllArtists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetAllArtists(ctx, req.(*GetAllArtistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_SearchArtists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchArtistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).SearchArtists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_SearchArtists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).SearchArtists(ctx, req.(*SearchArtistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetArtistsByIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArtistsByIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetArtistsByIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetArtistsByIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetArtistsByIDs(ctx, req.(*GetArtistsByIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetTracksByIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTracksByIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetTracksByIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetTracksByIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetTracksByIDs(ctx, req.(*GetTracksByIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetAlbumByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlbumByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetAlbumByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetAlbumByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetAlbumByID(ctx, req.(*GetAlbumByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetAllAlbums_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllAlbumsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetAllAlbums(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetAllAlbums_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetAllAlbums(ctx, req.(*GetAllAlbumsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetAlbumsByArtistID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlbumsByArtistIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetAlbumsByArtistID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetAlbumsByArtistID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetAlbumsByArtistID(ctx, req.(*GetAlbumsByArtistIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_SearchAlbums_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchAlbumsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).SearchAlbums(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_SearchAlbums_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).SearchAlbums(ctx, req.(*SearchAlbumsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetAlbumsByIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlbumsByIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetAlbumsByIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetAlbumsByIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetAlbumsByIDs(ctx, req.(*GetAlbumsByIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetTrackByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrackByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetTrackByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetTrackByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetTrackByID(ctx, req.(*GetTrackByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetAllTracks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllTracksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetAllTracks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetAllTracks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetAllTracks(ctx, req.(*GetAllTracksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetTracksByArtistID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTracksByArtistIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetTracksByArtistID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetTracksByArtistID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetTracksByArtistID(ctx, req.(*GetTracksByArtistIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetTracksByAlbumID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTracksByAlbumIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetTracksByAlbumID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetTracksByAlbumID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetTracksByAlbumID(ctx, req.(*GetTracksByAlbumIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetTracksByGenreID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTracksByGenreIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetTracksByGenreID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetTracksByGenreID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetTracksByGenreID(ctx, req.(*GetTracksByGenreIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_SearchTracks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchTracksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).SearchTracks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_SearchTracks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).SearchTracks(ctx, req.(*SearchTracksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_RegisterPlay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterPlayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).RegisterPlay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_RegisterPlay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).RegisterPlay(ctx, req.(*RegisterPlayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CatalogService_ServiceDesc is the grpc.ServiceDesc for CatalogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CatalogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "catalog.CatalogService",
	HandlerType: (*CatalogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetArtistByID",
			Handler:    _CatalogService_GetArtistByID_Handler,
		},
		{
			MethodName: "GetAllArtists",
			Handler:    _CatalogService_GetAllArtists_Handler,
		},
		{
			MethodName: "SearchArtists",
			Handler:    _CatalogService_SearchArtists_Handler,
		},
		{
			MethodName: "GetArtistsByIDs",
			Handler:    _CatalogService_GetArtistsByIDs_Handler,
		},
		{
			MethodName: "GetTracksByIDs",
			Handler:    _CatalogService_GetTracksByIDs_Handler,
		},
		{
			MethodName: "GetAlbumByID",
			Handler:    _CatalogService_GetAlbumByID_Handler,
		},
		{
			MethodName: "GetAllAlbums",
			Handler:    _CatalogService_GetAllAlbums_Handler,
		},
		{
			MethodName: "GetAlbumsByArtistID",
			Handler:    _CatalogService_GetAlbumsByArtistID_Handler,
		},
		{
			MethodName: "SearchAlbums",
			Handler:    _CatalogService_SearchAlbums_Handler,
		},
		{
			MethodName: "GetAlbumsByIDs",
			Handler:    _CatalogService_GetAlbumsByIDs_Handler,
		},
		{
			MethodName: "GetTrackByID",
			Handler:    _CatalogService_GetTrackByID_Handler,
		},
		{
			MethodName: "GetAllTracks",
			Handler:    _CatalogService_GetAllTracks_Handler,
		},
		{
			MethodName: "GetTracksByArtistID",
			Handler:    _CatalogService_GetTracksByArtistID_Handler,
		},
		{
			MethodName: "GetTracksByAlbumID",
			Handler:    _CatalogService_GetTracksByAlbumID_Handler,
		},
		{
			MethodName: "GetTracksByGenreID",
			Handler:    _CatalogService_GetTracksByGenreID_Handler,
		},
		{
			MethodName: "SearchTracks",
			Handler:    _CatalogService_SearchTracks_Handler,
		},
		{
			MethodName: "RegisterPlay",
			Handler:    _CatalogService_RegisterPlay_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/catalog/catalog.proto",
}
