// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson3b1bf41aDecodeSpotifyMicroservicesPlaylistDto(in *jlexer.Lexer, out *UploadPlaylistAvatarResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "avatar_url":
			if in.IsNull() {
				in.Skip()
			} else {
				out.URL = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3b1bf41aEncodeSpotifyMicroservicesPlaylistDto(out *jwriter.Writer, in UploadPlaylistAvatarResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"avatar_url\":"
		out.RawString(prefix[1:])
		out.String(string(in.URL))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UploadPlaylistAvatarResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3b1bf41aEncodeSpotifyMicroservicesPlaylistDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UploadPlaylistAvatarResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3b1bf41aEncodeSpotifyMicroservicesPlaylistDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UploadPlaylistAvatarResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3b1bf41aDecodeSpotifyMicroservicesPlaylistDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UploadPlaylistAvatarResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3b1bf41aDecodeSpotifyMicroservicesPlaylistDto(l, v)
}
func easyjson3b1bf41aDecodeSpotifyMicroservicesPlaylistDto1(in *jlexer.Lexer, out *UpdatePlaylistRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "title":
			if in.IsNull() {
				in.Skip()
				out.Title = nil
			} else {
				if out.Title == nil {
					out.Title = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Title = string(in.String())
				}
			}
		case "description":
			if in.IsNull() {
				in.Skip()
				out.Description = nil
			} else {
				if out.Description == nil {
					out.Description = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Description = string(in.String())
				}
			}
		case "is_favorite":
			if in.IsNull() {
				in.Skip()
				out.IsFavorite = nil
			} else {
				if out.IsFavorite == nil {
					out.IsFavorite = new(bool)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.IsFavorite = bool(in.Bool())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3b1bf41aEncodeSpotifyMicroservicesPlaylistDto1(out *jwriter.Writer, in UpdatePlaylistRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"title\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.Title == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Title))
		}
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		if in.Description == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Description))
		}
	}
	{
		const prefix string = ",\"is_favorite\":"
		out.RawString(prefix)
		if in.IsFavorite == nil {
			out.RawString("null")
		} else {
			out.Bool(bool(*in.IsFavorite))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UpdatePlaylistRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3b1bf41aEncodeSpotifyMicroservicesPlaylistDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UpdatePlaylistRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3b1bf41aEncodeSpotifyMicroservicesPlaylistDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UpdatePlaylistRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3b1bf41aDecodeSpotifyMicroservicesPlaylistDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UpdatePlaylistRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3b1bf41aDecodeSpotifyMicroservicesPlaylistDto1(l, v)
}
func easyjson3b1bf41aDecodeSpotifyMicroservicesPlaylistDto2(in *jlexer.Lexer, out *Track) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "duration_s":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DurationS = int(in.Int())
			}
		case "file_url":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FileURL = string(in.String())
			}
		case "artists":
			if in.IsNull() {
				in.Skip()
				out.Artists = nil
			} else {
				in.Delim('[')
				if out.Artists == nil {
					if !in.IsDelim(']') {
						out.Artists = make([]Artist, 0, 2)
					} else {
						out.Artists = []Artist{}
					}
				} else {
					out.Artists = (out.Artists)[:0]
				}
				for !in.IsDelim(']') {
					var v1 Artist
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Artists = append(out.Artists, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "album":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Album).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3b1bf41aEncodeSpotifyMicroservicesPlaylistDto2(out *jwriter.Writer, in Track) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"duration_s\":"
		out.RawString(prefix)
		out.Int(int(in.DurationS))
	}
	{
		const prefix string = ",\"file_url\":"
		out.RawString(prefix)
		out.String(string(in.FileURL))
	}
	{
		const prefix string = ",\"artists\":"
		out.RawString(prefix)
		if in.Artists == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Artists {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"album\":"
		out.RawString(prefix)
		(in.Album).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Track) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3b1bf41aEncodeSpotifyMicroservicesPlaylistDto2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Track) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3b1bf41aEncodeSpotifyMicroservicesPlaylistDto2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Track) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3b1bf41aDecodeSpotifyMicroservicesPlaylistDto2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Track) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3b1bf41aDecodeSpotifyMicroservicesPlaylistDto2(l, v)
}
func easyjson3b1bf41aDecodeSpotifyMicroservicesPlaylistDto3(in *jlexer.Lexer, out *RemoveTrackFromPlaylistRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "track_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TrackID = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3b1bf41aEncodeSpotifyMicroservicesPlaylistDto3(out *jwriter.Writer, in RemoveTrackFromPlaylistRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"track_id\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.TrackID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RemoveTrackFromPlaylistRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3b1bf41aEncodeSpotifyMicroservicesPlaylistDto3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RemoveTrackFromPlaylistRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3b1bf41aEncodeSpotifyMicroservicesPlaylistDto3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RemoveTrackFromPlaylistRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3b1bf41aDecodeSpotifyMicroservicesPlaylistDto3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RemoveTrackFromPlaylistRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3b1bf41aDecodeSpotifyMicroservicesPlaylistDto3(l, v)
}
func easyjson3b1bf41aDecodeSpotifyMicroservicesPlaylistDto4(in *jlexer.Lexer, out *Playlist) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "creator_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CreatorID = string(in.String())
			}
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "description":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Description = string(in.String())
			}
		case "is_favorite":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsFavorite = bool(in.Bool())
			}
		case "avatar_url":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AvatarURL = string(in.String())
			}
		case "tracks":
			if in.IsNull() {
				in.Skip()
				out.Tracks = nil
			} else {
				in.Delim('[')
				if out.Tracks == nil {
					if !in.IsDelim(']') {
						out.Tracks = make([]Track, 0, 0)
					} else {
						out.Tracks = []Track{}
					}
				} else {
					out.Tracks = (out.Tracks)[:0]
				}
				for !in.IsDelim(']') {
					var v4 Track
					if in.IsNull() {
						in.Skip()
					} else {
						(v4).UnmarshalEasyJSON(in)
					}
					out.Tracks = append(out.Tracks, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3b1bf41aEncodeSpotifyMicroservicesPlaylistDto4(out *jwriter.Writer, in Playlist) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"creator_id\":"
		out.RawString(prefix)
		out.String(string(in.CreatorID))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	if in.Description != "" {
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"is_favorite\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsFavorite))
	}
	if in.AvatarURL != "" {
		const prefix string = ",\"avatar_url\":"
		out.RawString(prefix)
		out.String(string(in.AvatarURL))
	}
	if len(in.Tracks) != 0 {
		const prefix string = ",\"tracks\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v5, v6 := range in.Tracks {
				if v5 > 0 {
					out.RawByte(',')
				}
				(v6).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Playlist) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3b1bf41aEncodeSpotifyMicroservicesPlaylistDto4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Playlist) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3b1bf41aEncodeSpotifyMicroservicesPlaylistDto4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Playlist) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3b1bf41aDecodeSpotifyMicroservicesPlaylistDto4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Playlist) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3b1bf41aDecodeSpotifyMicroservicesPlaylistDto4(l, v)
}
func easyjson3b1bf41aDecodeSpotifyMicroservicesPlaylistDto5(in *jlexer.Lexer, out *GeneratedMeta) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "description":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Description = string(in.String())
			}
		case "source":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Source = string(in.String())
			}
		case "warning":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Warning = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3b1bf41aEncodeSpotifyMicroservicesPlaylistDto5(out *jwriter.Writer, in GeneratedMeta) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix[1:])
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"source\":"
		out.RawString(prefix)
		out.String(string(in.Source))
	}
	if in.Warning != "" {
		const prefix string = ",\"warning\":"
		out.RawString(prefix)
		out.String(string(in.Warning))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GeneratedMeta) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3b1bf41aEncodeSpotifyMicroservicesPlaylistDto5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GeneratedMeta) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3b1bf41aEncodeSpotifyMicroservicesPlaylistDto5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GeneratedMeta) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3b1bf41aDecodeSpotifyMicroservicesPlaylistDto5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GeneratedMeta) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3b1bf41aDecodeSpotifyMicroservicesPlaylistDto5(l, v)
}
func easyjson3b1bf41aDecodeSpotifyMicroservicesPlaylistDto6(in *jlexer.Lexer, out *FavoriteArtist) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "creator_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CreatorID = string(in.String())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "avatar_url":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AvatarURL = string(in.String())
			}
		case "play_count":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PlayCount = int64(in.Int64())
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3b1bf41aEncodeSpotifyMicroservicesPlaylistDto6(out *jwriter.Writer, in FavoriteArtist) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"creator_id\":"
		out.RawString(prefix)
		out.String(string(in.CreatorID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	if in.AvatarURL != "" {
		const prefix string = ",\"avatar_url\":"
		out.RawString(prefix)
		out.String(string(in.AvatarURL))
	}
	{
		const prefix string = ",\"play_count\":"
		out.RawString(prefix)
		out.Int64(int64(in.PlayCount))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FavoriteArtist) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3b1bf41aEncodeSpotifyMicroservicesPlaylistDto6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FavoriteArtist) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3b1bf41aEncodeSpotifyMicroservicesPlaylistDto6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FavoriteArtist) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3b1bf41aDecodeSpotifyMicroservicesPlaylistDto6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FavoriteArtist) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3b1bf41aDecodeSpotifyMicroservicesPlaylistDto6(l, v)
}
func easyjson3b1bf41aDecodeSpotifyMicroservicesPlaylistDto7(in *jlexer.Lexer, out *FavoriteAlbum) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "creator_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CreatorID = string(in.String())
			}
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "avatar_url":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AvatarURL = string(in.String())
			}
		case "artists":
			if in.IsNull() {
				in.Skip()
				out.Artists = nil
			} else {
				in.Delim('[')
				if out.Artists == nil {
					if !in.IsDelim(']') {
						out.Artists = make([]ArtistForAlbum, 0, 2)
					} else {
						out.Artists = []ArtistForAlbum{}
					}
				} else {
					out.Artists = (out.Artists)[:0]
				}
				for !in.IsDelim(']') {
					var v7 ArtistForAlbum
					if in.IsNull() {
						in.Skip()
					} else {
						(v7).UnmarshalEasyJSON(in)
					}
					out.Artists = append(out.Artists, v7)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3b1bf41aEncodeSpotifyMicroservicesPlaylistDto7(out *jwriter.Writer, in FavoriteAlbum) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"creator_id\":"
		out.RawString(prefix)
		out.String(string(in.CreatorID))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	if in.AvatarURL != "" {
		const prefix string = ",\"avatar_url\":"
		out.RawString(prefix)
		out.String(string(in.AvatarURL))
	}
	{
		const prefix string = ",\"artists\":"
		out.RawString(prefix)
		if in.Artists == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v8, v9 := range in.Artists {
				if v8 > 0 {
					out.RawByte(',')
				}
				(v9).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FavoriteAlbum) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3b1bf41aEncodeSpotifyMicroservicesPlaylistDto7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FavoriteAlbum) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3b1bf41aEncodeSpotifyMicroservicesPlaylistDto7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FavoriteAlbum) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3b1bf41aDecodeSpotifyMicroservicesPlaylistDto7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FavoriteAlbum) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3b1bf41aDecodeSpotifyMicroservicesPlaylistDto7(l, v)
}
func easyjson3b1bf41aDecodeSpotifyMicroservicesPlaylistDto8(in *jlexer.Lexer, out *CreatePlaylistRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "description":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Description = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3b1bf41aEncodeSpotifyMicroservicesPlaylistDto8(out *jwriter.Writer, in CreatePlaylistRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"title\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreatePlaylistRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3b1bf41aEncodeSpotifyMicroservicesPlaylistDto8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreatePlaylistRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3b1bf41aEncodeSpotifyMicroservicesPlaylistDto8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreatePlaylistRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3b1bf41aDecodeSpotifyMicroservicesPlaylistDto8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreatePlaylistRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3b1bf41aDecodeSpotifyMicroservicesPlaylistDto8(l, v)
}
func easyjson3b1bf41aDecodeSpotifyMicroservicesPlaylistDto9(in *jlexer.Lexer, out *ConfirmGeneratedMetaRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "description":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Description = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3b1bf41aEncodeSpotifyMicroservicesPlaylistDto9(out *jwriter.Writer, in ConfirmGeneratedMetaRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix[1:])
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ConfirmGeneratedMetaRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3b1bf41aEncodeSpotifyMicroservicesPlaylistDto9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ConfirmGeneratedMetaRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3b1bf41aEncodeSpotifyMicroservicesPlaylistDto9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ConfirmGeneratedMetaRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3b1bf41aDecodeSpotifyMicroservicesPlaylistDto9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ConfirmGeneratedMetaRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3b1bf41aDecodeSpotifyMicroservicesPlaylistDto9(l, v)
}
func easyjson3b1bf41aDecodeSpotifyMicroservicesPlaylistDto10(in *jlexer.Lexer, out *ArtistForAlbum) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3b1bf41aEncodeSpotifyMicroservicesPlaylistDto10(out *jwriter.Writer, in ArtistForAlbum) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ArtistForAlbum) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3b1bf41aEncodeSpotifyMicroservicesPlaylistDto10(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ArtistForAlbum) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3b1bf41aEncodeSpotifyMicroservicesPlaylistDto10(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ArtistForAlbum) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3b1bf41aDecodeSpotifyMicroservicesPlaylistDto10(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ArtistForAlbum) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3b1bf41aDecodeSpotifyMicroservicesPlaylistDto10(l, v)
}
func easyjson3b1bf41aDecodeSpotifyMicroservicesPlaylistDto11(in *jlexer.Lexer, out *Artist) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3b1bf41aEncodeSpotifyMicroservicesPlaylistDto11(out *jwriter.Writer, in Artist) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Artist) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3b1bf41aEncodeSpotifyMicroservicesPlaylistDto11(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Artist) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3b1bf41aEncodeSpotifyMicroservicesPlaylistDto11(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Artist) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3b1bf41aDecodeSpotifyMicroservicesPlaylistDto11(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Artist) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3b1bf41aDecodeSpotifyMicroservicesPlaylistDto11(l, v)
}
func easyjson3b1bf41aDecodeSpotifyMicroservicesPlaylistDto12(in *jlexer.Lexer, out *Album) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "avatar_url":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AvatarURL = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3b1bf41aEncodeSpotifyMicroservicesPlaylistDto12(out *jwriter.Writer, in Album) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	if in.AvatarURL != "" {
		const prefix string = ",\"avatar_url\":"
		out.RawString(prefix)
		out.String(string(in.AvatarURL))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Album) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3b1bf41aEncodeSpotifyMicroservicesPlaylistDto12(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Album) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3b1bf41aEncodeSpotifyMicroservicesPlaylistDto12(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Album) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3b1bf41aDecodeSpotifyMicroservicesPlaylistDto12(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Album) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3b1bf41aDecodeSpotifyMicroservicesPlaylistDto12(l, v)
}
func easyjson3b1bf41aDecodeSpotifyMicroservicesPlaylistDto13(in *jlexer.Lexer, out *AddTrackToPlaylistRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "track_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TrackID = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3b1bf41aEncodeSpotifyMicroservicesPlaylistDto13(out *jwriter.Writer, in AddTrackToPlaylistRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"track_id\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.TrackID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AddTrackToPlaylistRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3b1bf41aEncodeSpotifyMicroservicesPlaylistDto13(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AddTrackToPlaylistRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3b1bf41aEncodeSpotifyMicroservicesPlaylistDto13(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AddTrackToPlaylistRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3b1bf41aDecodeSpotifyMicroservicesPlaylistDto13(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AddTrackToPlaylistRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3b1bf41aDecodeSpotifyMicroservicesPlaylistDto13(l, v)
}
func easyjson3b1bf41aDecodeSpotifyMicroservicesPlaylistDto14(in *jlexer.Lexer, out *AddTrackToFavoriteRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "track_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TrackID = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3b1bf41aEncodeSpotifyMicroservicesPlaylistDto14(out *jwriter.Writer, in AddTrackToFavoriteRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"track_id\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.TrackID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AddTrackToFavoriteRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3b1bf41aEncodeSpotifyMicroservicesPlaylistDto14(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AddTrackToFavoriteRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3b1bf41aEncodeSpotifyMicroservicesPlaylistDto14(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AddTrackToFavoriteRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3b1bf41aDecodeSpotifyMicroservicesPlaylistDto14(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AddTrackToFavoriteRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3b1bf41aDecodeSpotifyMicroservicesPlaylistDto14(l, v)
}
