REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM auth_user;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM auth_user;
REVOKE USAGE ON SCHEMA public FROM auth_user;
REVOKE CONNECT ON DATABASE mydb FROM auth_user;

REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM catalog_user;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM catalog_user;
REVOKE USAGE ON SCHEMA public FROM catalog_user;
REVOKE CONNECT ON DATABASE mydb FROM catalog_user;

REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM playlist_user;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM playlist_user;
REVOKE USAGE ON SCHEMA public FROM playlist_user;
REVOKE CONNECT ON DATABASE mydb FROM playlist_user;

DROP USER IF EXISTS auth_user;
DROP USER IF EXISTS catalog_user;
DROP USER IF EXISTS playlist_user;
