// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package http

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson5205c11aDecodeSpotifyMicroservicesAuthDeliveryHttp(in *jlexer.Lexer, out *csrfResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "csrf_token":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Token = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5205c11aEncodeSpotifyMicroservicesAuthDeliveryHttp(out *jwriter.Writer, in csrfResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"csrf_token\":"
		out.RawString(prefix[1:])
		out.String(string(in.Token))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v csrfResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5205c11aEncodeSpotifyMicroservicesAuthDeliveryHttp(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v csrfResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5205c11aEncodeSpotifyMicroservicesAuthDeliveryHttp(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *csrfResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5205c11aDecodeSpotifyMicroservicesAuthDeliveryHttp(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *csrfResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5205c11aDecodeSpotifyMicroservicesAuthDeliveryHttp(l, v)
}
