shared_preload_libraries = 'pg_stat_statements,auto_explain'

pg_stat_statements.max = 10000
pg_stat_statements.track = all

log_destination = 'stderr'
logging_collector = on

log_directory = 'pg_log'
log_filename = 'postgresql-%Y-%m-%d.log'
log_file_mode = 0644

log_line_prefix = '%t [%p]: [%l-1] user=%u,db=%d,app=%a,host=%h '
log_min_duration_statement = 500
log_lock_waits = on

auto_explain.log_min_duration = 2000
auto_explain.log_analyze = on
auto_explain.log_verbose = on
auto_explain.log_buffers = on

statement_timeout = 5s
lock_timeout = 1s

max_connections = 100

listen_addresses = '0.0.0.0'

