auth:
  http:
    port: "8080"
    readTimeout: 5s
    writeTimeout: 10s
    idleTimeout: 60s
    shutdownTimeout: 15s
    cors:
      allowedOrigins:
        - "http://localhost:8090"
        - "http://217.16.17.173:8090"
        - "https://wave-music.ru"
        - "https://www.wave-music.ru"
      allowedMethods: ["GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"]
      allowedHeaders:
        ["Content-Type", "Authorization", "X-Requested-With", "X-CSRF-Token"]
      allowCredentials: true
    allowedAvatarTypes:
      - "image/png"
      - "image/jpeg"
      - "image/webp"
      - "image/jpg"
      - "image/gif"
      - "image/bmp"
      - "image/svg"
      - "image/avif"
      - "image/heic"
      - "image/heif"
      - "image/ico"
    auth:
      jwt:
        secretKey: "dev-jwt-secret"
        accessTokenTTL: 720h
      csrf:
        secretKey: "dev-csrf-secret"
        tokenTTL: 15m
  grpc:
    port: "9001"
  logger:
    level: "info"
    mode: "prod"

catalog:
  http:
    port: "8081"
    readTimeout: 5s
    writeTimeout: 10s
    idleTimeout: 60s
    shutdownTimeout: 15s
    cors:
      allowedOrigins:
        - "http://localhost:8090"
        - "http://217.16.17.173:8090"
        - "https://wave-music.ru"
        - "https://www.wave-music.ru"
      allowedMethods: ["GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"]
      allowedHeaders:
        ["Content-Type", "Authorization", "X-Requested-With", "X-CSRF-Token"]
      allowCredentials: true
  grpc:
    port: "9000"
    clients:
      auth: "auth:9001"
  logger:
    level: "info"
    mode: "prod"

playlist:
  http:
    port: "8082"
    readTimeout: 5s
    writeTimeout: 10s
    idleTimeout: 60s
    shutdownTimeout: 15s
    cors:
      allowedOrigins:
        - "http://localhost:8090"
        - "http://217.16.17.173:8090"
        - "https://wave-music.ru"
        - "https://www.wave-music.ru"
      allowedMethods: ["GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"]
      allowedHeaders:
        ["Content-Type", "Authorization", "X-Requested-With", "X-CSRF-Token"]
      allowCredentials: true
    auth:
      jwt:
        secretKey: "dev-jwt-secret"
        accessTokenTTL: 720h
      csrf:
        secretKey: "dev-csrf-secret"
        tokenTTL: 15m

  logger:
    level: "info"
    mode: "prod"

  allowed_avatar_types:
    - "image/png"
    - "image/jpeg"
    - "image/webp"
    - "image/jpg"
    - "image/gif"
    - "image/bmp"
    - "image/svg"
    - "image/avif"
    - "image/heic"
    - "image/heif"
    - "image/ico"

  buckets:
    avatars: "avatars"

  clients:
    catalog: "catalog:9000"
    auth: "auth:9001"

db:
  host: "db"
  port: 5432
  user: "myuser"
  password: "mypassword"
  dbName: "mydb"
  sslmode: "disable"
  maxOpenConns: 25
  maxIdleConns: 25
  connMaxLifetime: 5m

minio:
  endpoint: "minio:9000"
  accessKey: "miniouser"
  secretKey: "miniopassword"
  bucket: "avatars"
  useSSL: false
