// Code generated by MockGen. DO NOT EDIT.
// Source: spotify/microservices/playlist/service (interfaces: IAIGenerator)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/ai/ai_mock.go -package=ai_mock spotify/microservices/playlist/service IAIGenerator
//

// Package ai_mock is a generated GoMock package.
package ai_mock

import (
	context "context"
	reflect "reflect"
	ai "spotify/internal/ai"
	dto "spotify/microservices/playlist/dto"

	gomock "go.uber.org/mock/gomock"
)

// MockIAIGenerator is a mock of IAIGenerator interface.
type MockIAIGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockIAIGeneratorMockRecorder
	isgomock struct{}
}

// MockIAIGeneratorMockRecorder is the mock recorder for MockIAIGenerator.
type MockIAIGeneratorMockRecorder struct {
	mock *MockIAIGenerator
}

// NewMockIAIGenerator creates a new mock instance.
func NewMockIAIGenerator(ctrl *gomock.Controller) *MockIAIGenerator {
	mock := &MockIAIGenerator{ctrl: ctrl}
	mock.recorder = &MockIAIGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAIGenerator) EXPECT() *MockIAIGeneratorMockRecorder {
	return m.recorder
}

// GeneratePlaylistMeta mocks base method.
func (m *MockIAIGenerator) GeneratePlaylistMeta(ctx context.Context, tracks []dto.Track) ([]ai.Meta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GeneratePlaylistMeta", ctx, tracks)
	ret0, _ := ret[0].([]ai.Meta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GeneratePlaylistMeta indicates an expected call of GeneratePlaylistMeta.
func (mr *MockIAIGeneratorMockRecorder) GeneratePlaylistMeta(ctx, tracks any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GeneratePlaylistMeta", reflect.TypeOf((*MockIAIGenerator)(nil).GeneratePlaylistMeta), ctx, tracks)
}
