// Code generated by MockGen. DO NOT EDIT.
// Source: ai.go
//
// Generated by this command:
//
//	mockgen -source=ai.go -destination=../mocks/ai/ai_mock.go -package=ai_mock
//

// Package ai_mock is a generated GoMock package.
package ai_mock

import (
	context "context"
	reflect "reflect"
	dto "spotify/microservices/playlist/dto"

	gomock "go.uber.org/mock/gomock"
)

// MockIAIGenerator is a mock of IAIGenerator interface.
type MockIAIGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockIAIGeneratorMockRecorder
	isgomock struct{}
}

// MockIAIGeneratorMockRecorder is the mock recorder for MockIAIGenerator.
type MockIAIGeneratorMockRecorder struct {
	mock *MockIAIGenerator
}

// NewMockIAIGenerator creates a new mock instance.
func NewMockIAIGenerator(ctrl *gomock.Controller) *MockIAIGenerator {
	mock := &MockIAIGenerator{ctrl: ctrl}
	mock.recorder = &MockIAIGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAIGenerator) EXPECT() *MockIAIGeneratorMockRecorder {
	return m.recorder
}

// GeneratePlaylistMeta mocks base method.
func (m *MockIAIGenerator) GeneratePlaylistMeta(ctx context.Context, tracks []dto.Track) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GeneratePlaylistMeta", ctx, tracks)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GeneratePlaylistMeta indicates an expected call of GeneratePlaylistMeta.
func (mr *MockIAIGeneratorMockRecorder) GeneratePlaylistMeta(ctx, tracks any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GeneratePlaylistMeta", reflect.TypeOf((*MockIAIGenerator)(nil).GeneratePlaylistMeta), ctx, tracks)
}
