// Code generated by MockGen. DO NOT EDIT.
// Source: spotify/proto/catalog (interfaces: CatalogServiceClient)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/catalog/catalog_mock.go -package=catalog_mock spotify/proto/catalog CatalogServiceClient
//

// Package catalog_mock is a generated GoMock package.
package catalog_mock

import (
	context "context"
	reflect "reflect"
	catalog "spotify/proto/catalog"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockCatalogServiceClient is a mock of CatalogServiceClient interface.
type MockCatalogServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockCatalogServiceClientMockRecorder
	isgomock struct{}
}

// MockCatalogServiceClientMockRecorder is the mock recorder for MockCatalogServiceClient.
type MockCatalogServiceClientMockRecorder struct {
	mock *MockCatalogServiceClient
}

// NewMockCatalogServiceClient creates a new mock instance.
func NewMockCatalogServiceClient(ctrl *gomock.Controller) *MockCatalogServiceClient {
	mock := &MockCatalogServiceClient{ctrl: ctrl}
	mock.recorder = &MockCatalogServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCatalogServiceClient) EXPECT() *MockCatalogServiceClientMockRecorder {
	return m.recorder
}

// GetAlbumByID mocks base method.
func (m *MockCatalogServiceClient) GetAlbumByID(ctx context.Context, in *catalog.GetAlbumByIDRequest, opts ...grpc.CallOption) (*catalog.Album, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAlbumByID", varargs...)
	ret0, _ := ret[0].(*catalog.Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAlbumByID indicates an expected call of GetAlbumByID.
func (mr *MockCatalogServiceClientMockRecorder) GetAlbumByID(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAlbumByID", reflect.TypeOf((*MockCatalogServiceClient)(nil).GetAlbumByID), varargs...)
}

// GetAlbumsByArtistID mocks base method.
func (m *MockCatalogServiceClient) GetAlbumsByArtistID(ctx context.Context, in *catalog.GetAlbumsByArtistIDRequest, opts ...grpc.CallOption) (*catalog.GetAllAlbumsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAlbumsByArtistID", varargs...)
	ret0, _ := ret[0].(*catalog.GetAllAlbumsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAlbumsByArtistID indicates an expected call of GetAlbumsByArtistID.
func (mr *MockCatalogServiceClientMockRecorder) GetAlbumsByArtistID(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAlbumsByArtistID", reflect.TypeOf((*MockCatalogServiceClient)(nil).GetAlbumsByArtistID), varargs...)
}

// GetAlbumsByIDs mocks base method.
func (m *MockCatalogServiceClient) GetAlbumsByIDs(ctx context.Context, in *catalog.GetAlbumsByIDsRequest, opts ...grpc.CallOption) (*catalog.GetAllAlbumsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAlbumsByIDs", varargs...)
	ret0, _ := ret[0].(*catalog.GetAllAlbumsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAlbumsByIDs indicates an expected call of GetAlbumsByIDs.
func (mr *MockCatalogServiceClientMockRecorder) GetAlbumsByIDs(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAlbumsByIDs", reflect.TypeOf((*MockCatalogServiceClient)(nil).GetAlbumsByIDs), varargs...)
}

// GetAllAlbums mocks base method.
func (m *MockCatalogServiceClient) GetAllAlbums(ctx context.Context, in *catalog.GetAllAlbumsRequest, opts ...grpc.CallOption) (*catalog.GetAllAlbumsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAllAlbums", varargs...)
	ret0, _ := ret[0].(*catalog.GetAllAlbumsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllAlbums indicates an expected call of GetAllAlbums.
func (mr *MockCatalogServiceClientMockRecorder) GetAllAlbums(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllAlbums", reflect.TypeOf((*MockCatalogServiceClient)(nil).GetAllAlbums), varargs...)
}

// GetAllArtists mocks base method.
func (m *MockCatalogServiceClient) GetAllArtists(ctx context.Context, in *catalog.GetAllArtistsRequest, opts ...grpc.CallOption) (*catalog.GetAllArtistsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAllArtists", varargs...)
	ret0, _ := ret[0].(*catalog.GetAllArtistsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllArtists indicates an expected call of GetAllArtists.
func (mr *MockCatalogServiceClientMockRecorder) GetAllArtists(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllArtists", reflect.TypeOf((*MockCatalogServiceClient)(nil).GetAllArtists), varargs...)
}

// GetAllTracks mocks base method.
func (m *MockCatalogServiceClient) GetAllTracks(ctx context.Context, in *catalog.GetAllTracksRequest, opts ...grpc.CallOption) (*catalog.GetAllTracksResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAllTracks", varargs...)
	ret0, _ := ret[0].(*catalog.GetAllTracksResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllTracks indicates an expected call of GetAllTracks.
func (mr *MockCatalogServiceClientMockRecorder) GetAllTracks(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTracks", reflect.TypeOf((*MockCatalogServiceClient)(nil).GetAllTracks), varargs...)
}

// GetArtistByID mocks base method.
func (m *MockCatalogServiceClient) GetArtistByID(ctx context.Context, in *catalog.GetArtistByIDRequest, opts ...grpc.CallOption) (*catalog.Artist, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetArtistByID", varargs...)
	ret0, _ := ret[0].(*catalog.Artist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArtistByID indicates an expected call of GetArtistByID.
func (mr *MockCatalogServiceClientMockRecorder) GetArtistByID(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArtistByID", reflect.TypeOf((*MockCatalogServiceClient)(nil).GetArtistByID), varargs...)
}

// GetArtistsByIDs mocks base method.
func (m *MockCatalogServiceClient) GetArtistsByIDs(ctx context.Context, in *catalog.GetArtistsByIDsRequest, opts ...grpc.CallOption) (*catalog.GetArtistsByIDsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetArtistsByIDs", varargs...)
	ret0, _ := ret[0].(*catalog.GetArtistsByIDsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArtistsByIDs indicates an expected call of GetArtistsByIDs.
func (mr *MockCatalogServiceClientMockRecorder) GetArtistsByIDs(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArtistsByIDs", reflect.TypeOf((*MockCatalogServiceClient)(nil).GetArtistsByIDs), varargs...)
}

// GetTrackByID mocks base method.
func (m *MockCatalogServiceClient) GetTrackByID(ctx context.Context, in *catalog.GetTrackByIDRequest, opts ...grpc.CallOption) (*catalog.Track, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetTrackByID", varargs...)
	ret0, _ := ret[0].(*catalog.Track)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTrackByID indicates an expected call of GetTrackByID.
func (mr *MockCatalogServiceClientMockRecorder) GetTrackByID(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrackByID", reflect.TypeOf((*MockCatalogServiceClient)(nil).GetTrackByID), varargs...)
}

// GetTracksByAlbumID mocks base method.
func (m *MockCatalogServiceClient) GetTracksByAlbumID(ctx context.Context, in *catalog.GetTracksByAlbumIDRequest, opts ...grpc.CallOption) (*catalog.GetAllTracksResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetTracksByAlbumID", varargs...)
	ret0, _ := ret[0].(*catalog.GetAllTracksResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTracksByAlbumID indicates an expected call of GetTracksByAlbumID.
func (mr *MockCatalogServiceClientMockRecorder) GetTracksByAlbumID(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTracksByAlbumID", reflect.TypeOf((*MockCatalogServiceClient)(nil).GetTracksByAlbumID), varargs...)
}

// GetTracksByArtistID mocks base method.
func (m *MockCatalogServiceClient) GetTracksByArtistID(ctx context.Context, in *catalog.GetTracksByArtistIDRequest, opts ...grpc.CallOption) (*catalog.GetAllTracksResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetTracksByArtistID", varargs...)
	ret0, _ := ret[0].(*catalog.GetAllTracksResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTracksByArtistID indicates an expected call of GetTracksByArtistID.
func (mr *MockCatalogServiceClientMockRecorder) GetTracksByArtistID(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTracksByArtistID", reflect.TypeOf((*MockCatalogServiceClient)(nil).GetTracksByArtistID), varargs...)
}

// GetTracksByGenreID mocks base method.
func (m *MockCatalogServiceClient) GetTracksByGenreID(ctx context.Context, in *catalog.GetTracksByGenreIDRequest, opts ...grpc.CallOption) (*catalog.GetAllTracksResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetTracksByGenreID", varargs...)
	ret0, _ := ret[0].(*catalog.GetAllTracksResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTracksByGenreID indicates an expected call of GetTracksByGenreID.
func (mr *MockCatalogServiceClientMockRecorder) GetTracksByGenreID(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTracksByGenreID", reflect.TypeOf((*MockCatalogServiceClient)(nil).GetTracksByGenreID), varargs...)
}

// GetTracksByIDs mocks base method.
func (m *MockCatalogServiceClient) GetTracksByIDs(ctx context.Context, in *catalog.GetTracksByIDsRequest, opts ...grpc.CallOption) (*catalog.GetTracksByIDsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetTracksByIDs", varargs...)
	ret0, _ := ret[0].(*catalog.GetTracksByIDsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTracksByIDs indicates an expected call of GetTracksByIDs.
func (mr *MockCatalogServiceClientMockRecorder) GetTracksByIDs(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTracksByIDs", reflect.TypeOf((*MockCatalogServiceClient)(nil).GetTracksByIDs), varargs...)
}

// RegisterPlay mocks base method.
func (m *MockCatalogServiceClient) RegisterPlay(ctx context.Context, in *catalog.RegisterPlayRequest, opts ...grpc.CallOption) (*catalog.RegisterPlayResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RegisterPlay", varargs...)
	ret0, _ := ret[0].(*catalog.RegisterPlayResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterPlay indicates an expected call of RegisterPlay.
func (mr *MockCatalogServiceClientMockRecorder) RegisterPlay(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterPlay", reflect.TypeOf((*MockCatalogServiceClient)(nil).RegisterPlay), varargs...)
}

// SearchAlbums mocks base method.
func (m *MockCatalogServiceClient) SearchAlbums(ctx context.Context, in *catalog.SearchAlbumsRequest, opts ...grpc.CallOption) (*catalog.SearchAlbumsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SearchAlbums", varargs...)
	ret0, _ := ret[0].(*catalog.SearchAlbumsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchAlbums indicates an expected call of SearchAlbums.
func (mr *MockCatalogServiceClientMockRecorder) SearchAlbums(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchAlbums", reflect.TypeOf((*MockCatalogServiceClient)(nil).SearchAlbums), varargs...)
}

// SearchArtists mocks base method.
func (m *MockCatalogServiceClient) SearchArtists(ctx context.Context, in *catalog.SearchArtistsRequest, opts ...grpc.CallOption) (*catalog.SearchArtistsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SearchArtists", varargs...)
	ret0, _ := ret[0].(*catalog.SearchArtistsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchArtists indicates an expected call of SearchArtists.
func (mr *MockCatalogServiceClientMockRecorder) SearchArtists(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchArtists", reflect.TypeOf((*MockCatalogServiceClient)(nil).SearchArtists), varargs...)
}

// SearchTracks mocks base method.
func (m *MockCatalogServiceClient) SearchTracks(ctx context.Context, in *catalog.SearchTracksRequest, opts ...grpc.CallOption) (*catalog.SearchTracksResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SearchTracks", varargs...)
	ret0, _ := ret[0].(*catalog.SearchTracksResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchTracks indicates an expected call of SearchTracks.
func (mr *MockCatalogServiceClientMockRecorder) SearchTracks(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchTracks", reflect.TypeOf((*MockCatalogServiceClient)(nil).SearchTracks), varargs...)
}
