// Code generated by MockGen. DO NOT EDIT.
// Source: spotify/microservices/auth/delivery/http (interfaces: IService,CSRFManager)
//
// Generated by this command:
//
//	mockgen -destination=../../../../mocks/auth/service/service_mock.go -package=mock_auth_service spotify/microservices/auth/delivery/http IService,CSRFManager
//

// Package mock_auth_service is a generated GoMock package.
package mock_auth_service

import (
	context "context"
	reflect "reflect"
	dto "spotify/microservices/auth/dto"

	gomock "go.uber.org/mock/gomock"
)

// MockIService is a mock of IService interface.
type MockIService struct {
	ctrl     *gomock.Controller
	recorder *MockIServiceMockRecorder
	isgomock struct{}
}

// MockIServiceMockRecorder is the mock recorder for MockIService.
type MockIServiceMockRecorder struct {
	mock *MockIService
}

// NewMockIService creates a new mock instance.
func NewMockIService(ctrl *gomock.Controller) *MockIService {
	mock := &MockIService{ctrl: ctrl}
	mock.recorder = &MockIServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIService) EXPECT() *MockIServiceMockRecorder {
	return m.recorder
}

// DeleteAvatar mocks base method.
func (m *MockIService) DeleteAvatar(ctx context.Context, req dto.DeleteAvatarRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAvatar", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAvatar indicates an expected call of DeleteAvatar.
func (mr *MockIServiceMockRecorder) DeleteAvatar(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAvatar", reflect.TypeOf((*MockIService)(nil).DeleteAvatar), ctx, req)
}

// GetProfile mocks base method.
func (m *MockIService) GetProfile(ctx context.Context, req dto.GetProfileRequest) (*dto.GetProfileResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfile", ctx, req)
	ret0, _ := ret[0].(*dto.GetProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfile indicates an expected call of GetProfile.
func (mr *MockIServiceMockRecorder) GetProfile(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfile", reflect.TypeOf((*MockIService)(nil).GetProfile), ctx, req)
}

// Login mocks base method.
func (m *MockIService) Login(ctx context.Context, req dto.LoginRequest) (*dto.LoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, req)
	ret0, _ := ret[0].(*dto.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockIServiceMockRecorder) Login(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockIService)(nil).Login), ctx, req)
}

// Register mocks base method.
func (m *MockIService) Register(ctx context.Context, req dto.RegisterRequest) (*dto.RegisterResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, req)
	ret0, _ := ret[0].(*dto.RegisterResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockIServiceMockRecorder) Register(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockIService)(nil).Register), ctx, req)
}

// UpdateProfile mocks base method.
func (m *MockIService) UpdateProfile(ctx context.Context, req dto.UpdateProfileRequest) (*dto.UpdateProfileResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", ctx, req)
	ret0, _ := ret[0].(*dto.UpdateProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockIServiceMockRecorder) UpdateProfile(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockIService)(nil).UpdateProfile), ctx, req)
}

// UploadAvatar mocks base method.
func (m *MockIService) UploadAvatar(ctx context.Context, req dto.UploadAvatarRequest) (*dto.UploadAvatarResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadAvatar", ctx, req)
	ret0, _ := ret[0].(*dto.UploadAvatarResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadAvatar indicates an expected call of UploadAvatar.
func (mr *MockIServiceMockRecorder) UploadAvatar(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadAvatar", reflect.TypeOf((*MockIService)(nil).UploadAvatar), ctx, req)
}

// MockCSRFManager is a mock of CSRFManager interface.
type MockCSRFManager struct {
	ctrl     *gomock.Controller
	recorder *MockCSRFManagerMockRecorder
	isgomock struct{}
}

// MockCSRFManagerMockRecorder is the mock recorder for MockCSRFManager.
type MockCSRFManagerMockRecorder struct {
	mock *MockCSRFManager
}

// NewMockCSRFManager creates a new mock instance.
func NewMockCSRFManager(ctrl *gomock.Controller) *MockCSRFManager {
	mock := &MockCSRFManager{ctrl: ctrl}
	mock.recorder = &MockCSRFManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCSRFManager) EXPECT() *MockCSRFManagerMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockCSRFManager) Generate(userID, sessionID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", userID, sessionID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockCSRFManagerMockRecorder) Generate(userID, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockCSRFManager)(nil).Generate), userID, sessionID)
}
