// Code generated by MockGen. DO NOT EDIT.
// Source: spotify/microservices/catalog/delivery/http (interfaces: IService)
//
// Generated by this command:
//
//	mockgen -destination=../../../../mocks/catalog/service/service_mock.go -package=mock_catalog_service spotify/microservices/catalog/delivery/http IService
//

// Package mock_catalog_service is a generated GoMock package.
package mock_catalog_service

import (
	context "context"
	reflect "reflect"
	dto "spotify/microservices/catalog/dto"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockIService is a mock of IService interface.
type MockIService struct {
	ctrl     *gomock.Controller
	recorder *MockIServiceMockRecorder
	isgomock struct{}
}

// MockIServiceMockRecorder is the mock recorder for MockIService.
type MockIServiceMockRecorder struct {
	mock *MockIService
}

// NewMockIService creates a new mock instance.
func NewMockIService(ctrl *gomock.Controller) *MockIService {
	mock := &MockIService{ctrl: ctrl}
	mock.recorder = &MockIServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIService) EXPECT() *MockIServiceMockRecorder {
	return m.recorder
}

// GetAlbumByID mocks base method.
func (m *MockIService) GetAlbumByID(ctx context.Context, id uuid.UUID) (*dto.Album, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAlbumByID", ctx, id)
	ret0, _ := ret[0].(*dto.Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAlbumByID indicates an expected call of GetAlbumByID.
func (mr *MockIServiceMockRecorder) GetAlbumByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAlbumByID", reflect.TypeOf((*MockIService)(nil).GetAlbumByID), ctx, id)
}

// GetAlbumsByArtistID mocks base method.
func (m *MockIService) GetAlbumsByArtistID(ctx context.Context, artistID uuid.UUID, limit, offset uint64) ([]dto.Album, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAlbumsByArtistID", ctx, artistID, limit, offset)
	ret0, _ := ret[0].([]dto.Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAlbumsByArtistID indicates an expected call of GetAlbumsByArtistID.
func (mr *MockIServiceMockRecorder) GetAlbumsByArtistID(ctx, artistID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAlbumsByArtistID", reflect.TypeOf((*MockIService)(nil).GetAlbumsByArtistID), ctx, artistID, limit, offset)
}

// GetAllAlbums mocks base method.
func (m *MockIService) GetAllAlbums(ctx context.Context, limit, offset uint64) ([]dto.Album, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllAlbums", ctx, limit, offset)
	ret0, _ := ret[0].([]dto.Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllAlbums indicates an expected call of GetAllAlbums.
func (mr *MockIServiceMockRecorder) GetAllAlbums(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllAlbums", reflect.TypeOf((*MockIService)(nil).GetAllAlbums), ctx, limit, offset)
}

// GetAllArtists mocks base method.
func (m *MockIService) GetAllArtists(ctx context.Context, limit, offset uint64) ([]dto.Artist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllArtists", ctx, limit, offset)
	ret0, _ := ret[0].([]dto.Artist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllArtists indicates an expected call of GetAllArtists.
func (mr *MockIServiceMockRecorder) GetAllArtists(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllArtists", reflect.TypeOf((*MockIService)(nil).GetAllArtists), ctx, limit, offset)
}

// GetAllTracks mocks base method.
func (m *MockIService) GetAllTracks(ctx context.Context, limit, offset uint64) ([]dto.Track, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllTracks", ctx, limit, offset)
	ret0, _ := ret[0].([]dto.Track)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllTracks indicates an expected call of GetAllTracks.
func (mr *MockIServiceMockRecorder) GetAllTracks(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTracks", reflect.TypeOf((*MockIService)(nil).GetAllTracks), ctx, limit, offset)
}

// GetArtistByID mocks base method.
func (m *MockIService) GetArtistByID(ctx context.Context, id uuid.UUID) (*dto.Artist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArtistByID", ctx, id)
	ret0, _ := ret[0].(*dto.Artist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArtistByID indicates an expected call of GetArtistByID.
func (mr *MockIServiceMockRecorder) GetArtistByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArtistByID", reflect.TypeOf((*MockIService)(nil).GetArtistByID), ctx, id)
}

// GetCommentsByTrackID mocks base method.
func (m *MockIService) GetCommentsByTrackID(ctx context.Context, trackID uuid.UUID, limit, offset uint64) ([]dto.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommentsByTrackID", ctx, trackID, limit, offset)
	ret0, _ := ret[0].([]dto.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommentsByTrackID indicates an expected call of GetCommentsByTrackID.
func (mr *MockIServiceMockRecorder) GetCommentsByTrackID(ctx, trackID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommentsByTrackID", reflect.TypeOf((*MockIService)(nil).GetCommentsByTrackID), ctx, trackID, limit, offset)
}

// GetTrackByID mocks base method.
func (m *MockIService) GetTrackByID(ctx context.Context, id uuid.UUID) (*dto.Track, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrackByID", ctx, id)
	ret0, _ := ret[0].(*dto.Track)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTrackByID indicates an expected call of GetTrackByID.
func (mr *MockIServiceMockRecorder) GetTrackByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrackByID", reflect.TypeOf((*MockIService)(nil).GetTrackByID), ctx, id)
}

// GetTracksByAlbumID mocks base method.
func (m *MockIService) GetTracksByAlbumID(ctx context.Context, albumID uuid.UUID, limit, offset uint64) ([]dto.Track, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTracksByAlbumID", ctx, albumID, limit, offset)
	ret0, _ := ret[0].([]dto.Track)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTracksByAlbumID indicates an expected call of GetTracksByAlbumID.
func (mr *MockIServiceMockRecorder) GetTracksByAlbumID(ctx, albumID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTracksByAlbumID", reflect.TypeOf((*MockIService)(nil).GetTracksByAlbumID), ctx, albumID, limit, offset)
}

// GetTracksByArtistID mocks base method.
func (m *MockIService) GetTracksByArtistID(ctx context.Context, artistID uuid.UUID, limit, offset uint64) ([]dto.Track, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTracksByArtistID", ctx, artistID, limit, offset)
	ret0, _ := ret[0].([]dto.Track)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTracksByArtistID indicates an expected call of GetTracksByArtistID.
func (mr *MockIServiceMockRecorder) GetTracksByArtistID(ctx, artistID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTracksByArtistID", reflect.TypeOf((*MockIService)(nil).GetTracksByArtistID), ctx, artistID, limit, offset)
}

// GetTracksByGenreID mocks base method.
func (m *MockIService) GetTracksByGenreID(ctx context.Context, genreID uuid.UUID, limit, offset uint64) ([]dto.Track, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTracksByGenreID", ctx, genreID, limit, offset)
	ret0, _ := ret[0].([]dto.Track)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTracksByGenreID indicates an expected call of GetTracksByGenreID.
func (mr *MockIServiceMockRecorder) GetTracksByGenreID(ctx, genreID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTracksByGenreID", reflect.TypeOf((*MockIService)(nil).GetTracksByGenreID), ctx, genreID, limit, offset)
}

// PostComment mocks base method.
func (m *MockIService) PostComment(ctx context.Context, userID uuid.UUID, req dto.PostCommentRequest) (*dto.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostComment", ctx, userID, req)
	ret0, _ := ret[0].(*dto.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostComment indicates an expected call of PostComment.
func (mr *MockIServiceMockRecorder) PostComment(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostComment", reflect.TypeOf((*MockIService)(nil).PostComment), ctx, userID, req)
}

// RegisterPlay mocks base method.
func (m *MockIService) RegisterPlay(ctx context.Context, trackID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterPlay", ctx, trackID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterPlay indicates an expected call of RegisterPlay.
func (mr *MockIServiceMockRecorder) RegisterPlay(ctx, trackID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterPlay", reflect.TypeOf((*MockIService)(nil).RegisterPlay), ctx, trackID)
}

// SearchAlbums mocks base method.
func (m *MockIService) SearchAlbums(ctx context.Context, query string, limit uint64) ([]dto.AlbumSearch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchAlbums", ctx, query, limit)
	ret0, _ := ret[0].([]dto.AlbumSearch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchAlbums indicates an expected call of SearchAlbums.
func (mr *MockIServiceMockRecorder) SearchAlbums(ctx, query, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchAlbums", reflect.TypeOf((*MockIService)(nil).SearchAlbums), ctx, query, limit)
}

// SearchArtists mocks base method.
func (m *MockIService) SearchArtists(ctx context.Context, query string, limit uint64) ([]dto.ArtistSearch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchArtists", ctx, query, limit)
	ret0, _ := ret[0].([]dto.ArtistSearch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchArtists indicates an expected call of SearchArtists.
func (mr *MockIServiceMockRecorder) SearchArtists(ctx, query, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchArtists", reflect.TypeOf((*MockIService)(nil).SearchArtists), ctx, query, limit)
}

// SearchTracks mocks base method.
func (m *MockIService) SearchTracks(ctx context.Context, query string, limit uint64) ([]dto.TrackSearch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchTracks", ctx, query, limit)
	ret0, _ := ret[0].([]dto.TrackSearch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchTracks indicates an expected call of SearchTracks.
func (mr *MockIServiceMockRecorder) SearchTracks(ctx, query, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchTracks", reflect.TypeOf((*MockIService)(nil).SearchTracks), ctx, query, limit)
}
