// Code generated by MockGen. DO NOT EDIT.
// Source: spotify/internal/artist/delivery/http (interfaces: IService)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/artist/service_mock.go -package=artist spotify/internal/artist/delivery/http IService
//

// Package artist is a generated GoMock package.
package artist

import (
	context "context"
	reflect "reflect"
	dto "spotify/internal/artist/dto"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockIService is a mock of IService interface.
type MockIService struct {
	ctrl     *gomock.Controller
	recorder *MockIServiceMockRecorder
	isgomock struct{}
}

// MockIServiceMockRecorder is the mock recorder for MockIService.
type MockIServiceMockRecorder struct {
	mock *MockIService
}

// NewMockIService creates a new mock instance.
func NewMockIService(ctrl *gomock.Controller) *MockIService {
	mock := &MockIService{ctrl: ctrl}
	mock.recorder = &MockIServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIService) EXPECT() *MockIServiceMockRecorder {
	return m.recorder
}

// GetAllArtists mocks base method.
func (m *MockIService) GetAllArtists(ctx context.Context, limit, offset uint64) ([]dto.Artist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllArtists", ctx, limit, offset)
	ret0, _ := ret[0].([]dto.Artist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllArtists indicates an expected call of GetAllArtists.
func (mr *MockIServiceMockRecorder) GetAllArtists(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllArtists", reflect.TypeOf((*MockIService)(nil).GetAllArtists), ctx, limit, offset)
}

// GetArtistByID mocks base method.
func (m *MockIService) GetArtistByID(ctx context.Context, id uuid.UUID) (*dto.Artist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArtistByID", ctx, id)
	ret0, _ := ret[0].(*dto.Artist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArtistByID indicates an expected call of GetArtistByID.
func (mr *MockIServiceMockRecorder) GetArtistByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArtistByID", reflect.TypeOf((*MockIService)(nil).GetArtistByID), ctx, id)
}
