// Code generated by MockGen. DO NOT EDIT.
// Source: spotify/internal/artist/service (interfaces: ITrackService)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/artist/track_service_mock.go -package=artist spotify/internal/artist/service ITrackService
//

// Package artist is a generated GoMock package.
package artist

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockITrackService is a mock of ITrackService interface.
type MockITrackService struct {
	ctrl     *gomock.Controller
	recorder *MockITrackServiceMockRecorder
	isgomock struct{}
}

// MockITrackServiceMockRecorder is the mock recorder for MockITrackService.
type MockITrackServiceMockRecorder struct {
	mock *MockITrackService
}

// NewMockITrackService creates a new mock instance.
func NewMockITrackService(ctrl *gomock.Controller) *MockITrackService {
	mock := &MockITrackService{ctrl: ctrl}
	mock.recorder = &MockITrackServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITrackService) EXPECT() *MockITrackServiceMockRecorder {
	return m.recorder
}

// GetTotalPlaysByArtistID mocks base method.
func (m *MockITrackService) GetTotalPlaysByArtistID(ctx context.Context, artistID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalPlaysByArtistID", ctx, artistID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalPlaysByArtistID indicates an expected call of GetTotalPlaysByArtistID.
func (mr *MockITrackServiceMockRecorder) GetTotalPlaysByArtistID(ctx, artistID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalPlaysByArtistID", reflect.TypeOf((*MockITrackService)(nil).GetTotalPlaysByArtistID), ctx, artistID)
}

// GetTotalPlaysByArtistIDs mocks base method.
func (m *MockITrackService) GetTotalPlaysByArtistIDs(ctx context.Context, artistIDs []uuid.UUID) (map[uuid.UUID]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalPlaysByArtistIDs", ctx, artistIDs)
	ret0, _ := ret[0].(map[uuid.UUID]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalPlaysByArtistIDs indicates an expected call of GetTotalPlaysByArtistIDs.
func (mr *MockITrackServiceMockRecorder) GetTotalPlaysByArtistIDs(ctx, artistIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalPlaysByArtistIDs", reflect.TypeOf((*MockITrackService)(nil).GetTotalPlaysByArtistIDs), ctx, artistIDs)
}
