// Code generated by MockGen. DO NOT EDIT.
// Source: spotify/microservices/auth/delivery/grpc (interfaces: IUserService)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/grpc_service/user_service_mock.go -package=auth_mocks spotify/microservices/auth/delivery/grpc IUserService
//

// Package auth_mocks is a generated GoMock package.
package auth_mocks

import (
	context "context"
	reflect "reflect"
	dto "spotify/microservices/auth/dto"

	gomock "go.uber.org/mock/gomock"
)

// MockIUserService is a mock of IUserService interface.
type MockIUserService struct {
	ctrl     *gomock.Controller
	recorder *MockIUserServiceMockRecorder
	isgomock struct{}
}

// MockIUserServiceMockRecorder is the mock recorder for MockIUserService.
type MockIUserServiceMockRecorder struct {
	mock *MockIUserService
}

// NewMockIUserService creates a new mock instance.
func NewMockIUserService(ctrl *gomock.Controller) *MockIUserService {
	mock := &MockIUserService{ctrl: ctrl}
	mock.recorder = &MockIUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUserService) EXPECT() *MockIUserServiceMockRecorder {
	return m.recorder
}

// GetUsersBatch mocks base method.
func (m *MockIUserService) GetUsersBatch(ctx context.Context, ids []string) ([]dto.GetProfileResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersBatch", ctx, ids)
	ret0, _ := ret[0].([]dto.GetProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersBatch indicates an expected call of GetUsersBatch.
func (mr *MockIUserServiceMockRecorder) GetUsersBatch(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersBatch", reflect.TypeOf((*MockIUserService)(nil).GetUsersBatch), ctx, ids)
}
