// Code generated by MockGen. DO NOT EDIT.
// Source: spotify/microservices/playlist/delivery/http (interfaces: IService)
//
// Generated by this command:
//
//	mockgen -destination=../../../../mocks/playlist/service/service_mock.go -package=mock_playlist_service spotify/microservices/playlist/delivery/http IService
//

// Package mock_playlist_service is a generated GoMock package.
package mock_playlist_service

import (
	context "context"
	reflect "reflect"
	dto "spotify/microservices/playlist/dto"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockIService is a mock of IService interface.
type MockIService struct {
	ctrl     *gomock.Controller
	recorder *MockIServiceMockRecorder
	isgomock struct{}
}

// MockIServiceMockRecorder is the mock recorder for MockIService.
type MockIServiceMockRecorder struct {
	mock *MockIService
}

// NewMockIService creates a new mock instance.
func NewMockIService(ctrl *gomock.Controller) *MockIService {
	mock := &MockIService{ctrl: ctrl}
	mock.recorder = &MockIServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIService) EXPECT() *MockIServiceMockRecorder {
	return m.recorder
}

// AddAlbumToFavorite mocks base method.
func (m *MockIService) AddAlbumToFavorite(ctx context.Context, req dto.AddAlbumToFavoriteRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAlbumToFavorite", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddAlbumToFavorite indicates an expected call of AddAlbumToFavorite.
func (mr *MockIServiceMockRecorder) AddAlbumToFavorite(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAlbumToFavorite", reflect.TypeOf((*MockIService)(nil).AddAlbumToFavorite), ctx, req)
}

// AddArtistToFavorite mocks base method.
func (m *MockIService) AddArtistToFavorite(ctx context.Context, req dto.AddArtistToFavoriteRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddArtistToFavorite", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddArtistToFavorite indicates an expected call of AddArtistToFavorite.
func (mr *MockIServiceMockRecorder) AddArtistToFavorite(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddArtistToFavorite", reflect.TypeOf((*MockIService)(nil).AddArtistToFavorite), ctx, req)
}

// AddTrackToFavorite mocks base method.
func (m *MockIService) AddTrackToFavorite(ctx context.Context, req dto.AddTrackToFavoriteRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTrackToFavorite", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTrackToFavorite indicates an expected call of AddTrackToFavorite.
func (mr *MockIServiceMockRecorder) AddTrackToFavorite(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTrackToFavorite", reflect.TypeOf((*MockIService)(nil).AddTrackToFavorite), ctx, req)
}

// AddTrackToPlaylist mocks base method.
func (m *MockIService) AddTrackToPlaylist(ctx context.Context, req dto.AddTrackToPlaylistRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTrackToPlaylist", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTrackToPlaylist indicates an expected call of AddTrackToPlaylist.
func (mr *MockIServiceMockRecorder) AddTrackToPlaylist(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTrackToPlaylist", reflect.TypeOf((*MockIService)(nil).AddTrackToPlaylist), ctx, req)
}

// CreatePlaylist mocks base method.
func (m *MockIService) CreatePlaylist(ctx context.Context, req dto.CreatePlaylistRequest) (*dto.Playlist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePlaylist", ctx, req)
	ret0, _ := ret[0].(*dto.Playlist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePlaylist indicates an expected call of CreatePlaylist.
func (mr *MockIServiceMockRecorder) CreatePlaylist(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePlaylist", reflect.TypeOf((*MockIService)(nil).CreatePlaylist), ctx, req)
}

// DeletePlaylist mocks base method.
func (m *MockIService) DeletePlaylist(ctx context.Context, req dto.DeletePlaylistRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePlaylist", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePlaylist indicates an expected call of DeletePlaylist.
func (mr *MockIServiceMockRecorder) DeletePlaylist(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePlaylist", reflect.TypeOf((*MockIService)(nil).DeletePlaylist), ctx, req)
}

// DeletePlaylistAvatar mocks base method.
func (m *MockIService) DeletePlaylistAvatar(ctx context.Context, req dto.DeletePlaylistAvatarRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePlaylistAvatar", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePlaylistAvatar indicates an expected call of DeletePlaylistAvatar.
func (mr *MockIServiceMockRecorder) DeletePlaylistAvatar(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePlaylistAvatar", reflect.TypeOf((*MockIService)(nil).DeletePlaylistAvatar), ctx, req)
}

// GetFavoriteAlbums mocks base method.
func (m *MockIService) GetFavoriteAlbums(ctx context.Context, userID uuid.UUID) ([]dto.FavoriteAlbum, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFavoriteAlbums", ctx, userID)
	ret0, _ := ret[0].([]dto.FavoriteAlbum)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFavoriteAlbums indicates an expected call of GetFavoriteAlbums.
func (mr *MockIServiceMockRecorder) GetFavoriteAlbums(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFavoriteAlbums", reflect.TypeOf((*MockIService)(nil).GetFavoriteAlbums), ctx, userID)
}

// GetFavoriteArtists mocks base method.
func (m *MockIService) GetFavoriteArtists(ctx context.Context, userID uuid.UUID) ([]dto.FavoriteArtist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFavoriteArtists", ctx, userID)
	ret0, _ := ret[0].([]dto.FavoriteArtist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFavoriteArtists indicates an expected call of GetFavoriteArtists.
func (mr *MockIServiceMockRecorder) GetFavoriteArtists(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFavoriteArtists", reflect.TypeOf((*MockIService)(nil).GetFavoriteArtists), ctx, userID)
}

// GetFavoritePlaylist mocks base method.
func (m *MockIService) GetFavoritePlaylist(ctx context.Context, req dto.GetFavoritePlaylistRequest) (*dto.Playlist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFavoritePlaylist", ctx, req)
	ret0, _ := ret[0].(*dto.Playlist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFavoritePlaylist indicates an expected call of GetFavoritePlaylist.
func (mr *MockIServiceMockRecorder) GetFavoritePlaylist(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFavoritePlaylist", reflect.TypeOf((*MockIService)(nil).GetFavoritePlaylist), ctx, req)
}

// GetPlaylistWithTracks mocks base method.
func (m *MockIService) GetPlaylistWithTracks(ctx context.Context, id uuid.UUID) (*dto.Playlist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaylistWithTracks", ctx, id)
	ret0, _ := ret[0].(*dto.Playlist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaylistWithTracks indicates an expected call of GetPlaylistWithTracks.
func (mr *MockIServiceMockRecorder) GetPlaylistWithTracks(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaylistWithTracks", reflect.TypeOf((*MockIService)(nil).GetPlaylistWithTracks), ctx, id)
}

// GetPlaylistsByUser mocks base method.
func (m *MockIService) GetPlaylistsByUser(ctx context.Context, req dto.GetPlaylistsByUserRequest) ([]dto.Playlist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaylistsByUser", ctx, req)
	ret0, _ := ret[0].([]dto.Playlist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaylistsByUser indicates an expected call of GetPlaylistsByUser.
func (mr *MockIServiceMockRecorder) GetPlaylistsByUser(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaylistsByUser", reflect.TypeOf((*MockIService)(nil).GetPlaylistsByUser), ctx, req)
}

// RemoveAlbumFromFavorite mocks base method.
func (m *MockIService) RemoveAlbumFromFavorite(ctx context.Context, req dto.RemoveAlbumFromFavoriteRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAlbumFromFavorite", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAlbumFromFavorite indicates an expected call of RemoveAlbumFromFavorite.
func (mr *MockIServiceMockRecorder) RemoveAlbumFromFavorite(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAlbumFromFavorite", reflect.TypeOf((*MockIService)(nil).RemoveAlbumFromFavorite), ctx, req)
}

// RemoveArtistFromFavorite mocks base method.
func (m *MockIService) RemoveArtistFromFavorite(ctx context.Context, req dto.RemoveArtistFromFavoriteRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveArtistFromFavorite", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveArtistFromFavorite indicates an expected call of RemoveArtistFromFavorite.
func (mr *MockIServiceMockRecorder) RemoveArtistFromFavorite(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveArtistFromFavorite", reflect.TypeOf((*MockIService)(nil).RemoveArtistFromFavorite), ctx, req)
}

// RemoveTrackFromPlaylist mocks base method.
func (m *MockIService) RemoveTrackFromPlaylist(ctx context.Context, req dto.RemoveTrackFromPlaylistRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveTrackFromPlaylist", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveTrackFromPlaylist indicates an expected call of RemoveTrackFromPlaylist.
func (mr *MockIServiceMockRecorder) RemoveTrackFromPlaylist(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveTrackFromPlaylist", reflect.TypeOf((*MockIService)(nil).RemoveTrackFromPlaylist), ctx, req)
}

// UpdatePlaylist mocks base method.
func (m *MockIService) UpdatePlaylist(ctx context.Context, req dto.UpdatePlaylistRequest) (*dto.Playlist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePlaylist", ctx, req)
	ret0, _ := ret[0].(*dto.Playlist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePlaylist indicates an expected call of UpdatePlaylist.
func (mr *MockIServiceMockRecorder) UpdatePlaylist(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePlaylist", reflect.TypeOf((*MockIService)(nil).UpdatePlaylist), ctx, req)
}

// UploadPlaylistAvatar mocks base method.
func (m *MockIService) UploadPlaylistAvatar(ctx context.Context, req dto.UploadPlaylistAvatarRequest) (*dto.UploadPlaylistAvatarResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadPlaylistAvatar", ctx, req)
	ret0, _ := ret[0].(*dto.UploadPlaylistAvatarResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadPlaylistAvatar indicates an expected call of UploadPlaylistAvatar.
func (mr *MockIServiceMockRecorder) UploadPlaylistAvatar(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadPlaylistAvatar", reflect.TypeOf((*MockIService)(nil).UploadPlaylistAvatar), ctx, req)
}
